package editors.blockcode;

import editors.blockcode.BlockTypes.BlockParameter;
import editors.blockcode.BlockTypes.ParamType;
import editors.blockcode.BlockTypes.TimelineMarker;

/**
 * Block workspace -> Lua compiler, the successor of the legacy
 * `BlockCodeEditorState.generateLuaCode()` / `generateBlockCode()`.
 *
 * `generate()` turns the global workspace stacks plus the timeline entries into
 * a finished script, `statement()` / `expression()` compile a single block and
 * `expandTemplate()` expands the `lua` template of blocks that came from an
 * external config.
 *
 * `Block` is the in-memory node of the editor (`editors.blockcode.Block`) and is
 * read structurally: a node may link its following blocks through
 * `next`/`nextBlock` or carry them in a `stack`/`children`/`body` array, and an
 * input may hold a plain value or a nested reporter node. Block definitions
 * (`label`, `lua`, `hatLua`, `parameters`) are taken from the node itself or from
 * its `blockData`/`data` field. Nothing here throws: empty or malformed stacks are
 * skipped and unbalanced structures still produce the code the user built.
 *
 * Nesting is explicit, exactly like in the legacy editor: `end`, `else` and
 * `elseif` are blocks the user places, while a hat block closes itself with `end`
 * when its stack is not empty.
 */
class BlockLuaGenerator
{
	/** Text put in front of every generated script. */
	public static var header:String = "-- Generated by Parker Engine Block Editor\n\n";

	/** Generated Lua is indented with spaces, one level per nested block. */
	static inline var INDENT_UNIT:String = "    ";

	/** Cycle guard for linked stacks. */
	static inline var MAX_STACK_SIZE:Int = 4096;

	static final TYPE_FIELDS:Array<String> = ["type", "blockType", "kind"];
	static final DATA_FIELDS:Array<String> = ["blockData", "data", "def", "definition", "blockDef"];
	static final NEXT_FIELDS:Array<String> = ["next", "nextBlock", "rest", "nextInStack"];
	static final BODY_FIELDS:Array<String> = ["stack", "children", "body", "blocks", "statements"];
	static final INPUT_FIELDS:Array<String> = [
		"inputs",
		"inputFields",
		"values",
		"params",
		"args",
		"arguments",
		"inputValues",
		"parameters"
	];
	static final PARAM_DEF_FIELDS:Array<String> = ["parameters", "parameterDefs", "blockParameters", "paramDefs"];
	static final LABEL_FIELDS:Array<String> = ["label", "title", "displayName"];
	static final HAT_FIELDS:Array<String> = ["hatLua", "hat", "hatCode"];
	static final LUA_FIELDS:Array<String> = ["lua", "template", "luaTemplate", "luaCode", "code"];

	static final HAT_TYPES:Array<String> = [
		"onCreate",
		"onCreatePost",
		"onUpdate",
		"onUpdatePost",
		"onBeatHit",
		"onStepHit",
		"onDestroy",
		"onEvent"
	];

	static final CLOSER_TYPES:Array<String> = ["end", "else", "elseif"];
	static final OPENER_TYPES:Array<String> = ["if", "elseif", "else", "whileTrue"];

	// --- Public API ---

	public static function generate(globals:Array<Block>, timeline:Array<{marker:TimelineMarker, root:Block}>):String
	{
		var chunks:Array<String> = [];

		if (globals != null)
		{
			for (root in globals)
			{
				var lines:Array<String> = [];
				emitRoot(root, 0, lines);
				if (lines.length > 0)
					chunks.push(lines.join("\n"));
			}
		}

		var stepLines:Array<String> = [];
		emitStepFunction(timeline, stepLines);
		if (stepLines.length > 0)
			chunks.push(stepLines.join("\n"));

		var eventLines:Array<String> = [];
		emitEventFunction(timeline, eventLines);
		if (eventLines.length > 0)
			chunks.push(eventLines.join("\n"));

		if (chunks.length == 0)
			return header;
		return header + chunks.join("\n\n") + "\n";
	}

	/** Lua code of a single block used as a value (reporters and literals). */
	public static function expression(b:Block):String
	{
		return codeOf(b, 0);
	}

	/**
	 * Lua code of a single block used as a statement. Hat blocks expand to their
	 * `hatLua`; `generate()` is what lays out whole stacks and adds their `end`.
	 */
	public static function statement(b:Block):String
	{
		return codeOf(b, 0);
	}

	/**
	 * Expands an external block template. `$1`, `$2`... take the arguments in
	 * order, `${name}` takes the argument of the parameter called `name`. Unknown
	 * or out of range placeholders are left untouched, so a broken template still
	 * produces readable Lua.
	 */
	public static function expandTemplate(tpl:String, args:Array<String>, params:Array<BlockParameter>):String
	{
		if (tpl == null || tpl.length == 0)
			return "";

		var out:StringBuf = new StringBuf();
		var length:Int = tpl.length;
		var i:Int = 0;

		while (i < length)
		{
			if (tpl.charAt(i) != "$")
			{
				out.add(tpl.charAt(i));
				i++;
				continue;
			}

			if (i + 1 < length && tpl.charAt(i + 1) == "{")
			{
				var close:Int = tpl.indexOf("}", i + 2);
				if (close != -1)
				{
					var arg:String = argByName(tpl.substring(i + 2, close), args, params);
					if (arg != null)
					{
						out.add(arg);
						i = close + 1;
						continue;
					}
				}
				out.add(tpl.charAt(i));
				i++;
				continue;
			}

			var end:Int = i + 1;
			while (end < length && "0123456789".indexOf(tpl.charAt(end)) != -1)
				end++;

			if (end > i + 1)
			{
				var index:Null<Int> = Std.parseInt(tpl.substring(i + 1, end));
				if (index != null && index >= 1 && args != null && index <= args.length && args[index - 1] != null)
				{
					out.add(args[index - 1]);
					i = end;
					continue;
				}
				out.add(tpl.substring(i, end));
				i = end;
				continue;
			}

			out.add(tpl.charAt(i));
			i++;
		}

		return out.toString();
	}

	// --- Emission ---

	/**
	 * Emits a root stack: a hat block wraps its own stack and closes it with `end`,
	 * anything else is emitted as the chain it starts.
	 */
	static function emitRoot(root:Block, level:Int, out:Array<String>):Void
	{
		if (root == null)
			return;

		if (!isHat(root))
		{
			emitStack(root, level, level, out);
			return;
		}

		out.push(indent(level) + codeOf(root, level));

		var body:Array<Block> = bodyOf(root);
		if (body != null)
		{
			emitList(body, level + 1, level, out);
			out.push(indent(level) + "end");
			return;
		}

		var rest:Block = nextOf(root);
		if (rest != null)
			emitStack(rest, level + 1, level, out);

		// A hat always closes its function, even when nothing was placed under it; otherwise an
		// untouched event block would save an unterminated `function ...` into the script.
		out.push(indent(level) + "end");
	}

	static function emitStack(first:Block, level:Int, floor:Int, out:Array<String>):Void
	{
		var current:Block = first;
		var currentLevel:Int = level;
		var guard:Int = 0;

		while (current != null && guard++ < MAX_STACK_SIZE)
		{
			var next:Block = nextOf(current);
			currentLevel = emitBlock(current, currentLevel, floor, out);
			current = next;
		}
	}

	static function emitList(blocks:Array<Block>, level:Int, floor:Int, out:Array<String>):Void
	{
		if (blocks == null)
			return;

		var currentLevel:Int = level;
		var guard:Int = 0;

		for (block in blocks)
		{
			if (guard++ >= MAX_STACK_SIZE)
				break;
			currentLevel = emitBlock(block, currentLevel, floor, out);
		}
	}

	/** Emits one block, returns the nesting level the next block starts at. */
	static function emitBlock(b:Block, level:Int, floor:Int, out:Array<String>):Int
	{
		if (b == null)
			return level;

		var type:String = typeOf(b);
		var currentLevel:Int = level;

		if (CLOSER_TYPES.indexOf(type) != -1)
			currentLevel = Std.int(Math.max(floor, currentLevel - 1));
		out.push(indent(currentLevel) + codeOf(b, currentLevel));

		var body:Array<Block> = bodyOf(b);
		if (isHat(b) && body != null)
		{
			emitList(body, currentLevel + 1, currentLevel, out);
			out.push(indent(currentLevel) + "end");
			return currentLevel;
		}

		if (body != null)
			emitList(body, currentLevel + 1, currentLevel, out);
		if (isOpener(b))
			return currentLevel + 1;
		return currentLevel;
	}

	/** One shared `onStepHit()` running every timeline stack at its marker step. */
	static function emitStepFunction(timeline:Array<{marker:TimelineMarker, root:Block}>, out:Array<String>):Void
	{
		var steps:Array<Int> = [];
		var stacks:Array<Block> = [];

		if (timeline != null)
		{
			for (entry in timeline)
			{
				if (entry == null || entry.marker == null)
					continue;

				var root:Block = entry.root;
				if (root == null)
					root = Reflect.field(entry, "stack");
				if (root == null)
					continue;

				var step:Null<Int> = markerStep(entry.marker);
				if (step == null)
					continue;

				steps.push(step);
				stacks.push(root);
			}
		}

		if (steps.length == 0)
			return;

		var order:Array<Int> = [];
		for (i in 0...steps.length)
			order.push(i);

		order.sort(function(a:Int, b:Int):Int
		{
			return steps[a] - steps[b];
		});

		out.push("function onStepHit()");
		for (i in order)
		{
			out.push(INDENT_UNIT + "if curStep == " + steps[i] + " then");
			emitRoot(stacks[i], 2, out);
			out.push(INDENT_UNIT + "end");
		}
		out.push("end");
	}

	/** One shared `onEvent(n, v1, v2)` running the stacks of every named marker. */
	static function emitEventFunction(timeline:Array<{marker:TimelineMarker, root:Block}>, out:Array<String>):Void
	{
		var names:Array<String> = [];
		var stacks:Array<Array<Block>> = [];

		if (timeline != null)
		{
			for (entry in timeline)
			{
				if (entry == null || entry.marker == null)
					continue;

				var name:String = markerEventName(entry.marker);
				if (name == null || name.length == 0)
					continue;

				var root:Block = entry.root;
				if (root == null)
					root = Reflect.field(entry, "stack");
				if (root == null)
					continue;

				var index:Int = names.indexOf(name);
				if (index == -1)
				{
					names.push(name);
					stacks.push([root]);
				}
				else
				{
					stacks[index].push(root);
				}
			}
		}

		if (names.length == 0)
			return;

		out.push("function onEvent(n, v1, v2)");
		for (i in 0...names.length)
		{
			out.push(INDENT_UNIT + "if n == '" + escapeSingle(names[i]) + "' then");
			for (root in stacks[i])
				emitRoot(root, 2, out);
			out.push(INDENT_UNIT + "end");
		}
		out.push("end");
	}

	static function indent(level:Int):String
	{
		var out:String = "";
		for (i in 0...level)
			out += INDENT_UNIT;
		return out;
	}

	// --- Block code ---

	static function codeOf(b:Block, level:Int):String
	{
		if (b == null)
			return "";

		var type:String = typeOf(b);
		try
		{
			return codeFor(b, type, level);
		}
		catch (e:Dynamic)
		{
			return "-- " + (type.length > 0 ? type : "block");
		}
	}

	static function codeFor(b:Block, type:String, level:Int):String
	{
		// A block that carries its own Lua is emitted verbatim; hats always do.
		var hat:String = strProp(b, HAT_FIELDS);
		if (hat != null && hat.length > 0)
			return hat;

		switch (type)
		{
			// Events
			case "onCreate":
				return "function onCreate()";
			case "onCreatePost":
				return "function onCreatePost()";
			case "onUpdate":
				return "function onUpdate(elapsed)";
			case "onUpdatePost":
				return "function onUpdatePost(elapsed)";
			case "onBeatHit":
				return "function onBeatHit()";
			case "onStepHit":
				return "function onStepHit()";
			case "onDestroy":
				return "function onDestroy()";
			case "onEvent":
				return "function onEvent(n, v1, v2)";

			// Control
			case "if":
				return "if " + v(argText(b, 0, "true", level)) + " then";
			case "elseif":
				return "elseif " + v(argText(b, 0, "true", level)) + " then";
			case "else":
				return "else";
			case "end":
				return "end";
			case "wait":
				return "runTimer('timer', " + v(argText(b, 0, 1, level)) + ")";
			case "debugPrint":
				return "debugPrint(" + q(argText(b, 0, "hello", level)) + ")";
			case "close":
				return "close(true)";

			// Operators
			case "add":
				return "(" + v(argText(b, 0, 0, level)) + " + " + v(argText(b, 1, 0, level)) + ")";
			case "sub":
				return "(" + v(argText(b, 0, 0, level)) + " - " + v(argText(b, 1, 0, level)) + ")";
			case "mul":
				return "(" + v(argText(b, 0, 0, level)) + " * " + v(argText(b, 1, 0, level)) + ")";
			case "div":
				return "(" + v(argText(b, 0, 0, level)) + " / " + v(argText(b, 1, 0, level)) + ")";
			case "eq":
				return "(" + v(argText(b, 0, 0, level)) + " == " + v(argText(b, 1, 0, level)) + ")";
			case "gt":
				return "(" + v(argText(b, 0, 0, level)) + " > " + v(argText(b, 1, 0, level)) + ")";
			case "lt":
				return "(" + v(argText(b, 0, 0, level)) + " < " + v(argText(b, 1, 0, level)) + ")";
			case "and":
				return "(" + v(argText(b, 0, "true", level)) + " and " + v(argText(b, 1, "true", level)) + ")";
			case "or":
				return "(" + v(argText(b, 0, "true", level)) + " or " + v(argText(b, 1, "true", level)) + ")";
			case "not":
				return "(not " + v(argText(b, 0, "true", level)) + ")";
			case "join":
				return "(" + q(argText(b, 0, "a", level)) + " .. " + q(argText(b, 1, "b", level)) + ")";

			// Sensing
			case "keyJustPressed":
				return "keyJustPressed(" + q(argText(b, 0, "space", level)) + ")";
			case "keyPressed":
				return "keyPressed(" + q(argText(b, 0, "space", level)) + ")";
			case "curStep":
				return "curStep";
			case "curBeat":
				return "curBeat";
			case "songPosition":
				return "getSongPosition()";
			case "health":
				return "getProperty('health')";
			case "getPixelColor":
				return "getPixelColor("
					+ q(argText(b, 0, "obj", level))
					+ ", "
					+ v(argText(b, 1, 0, level))
					+ ", "
					+ v(argText(b, 2, 0, level))
					+ ")";

			// Looks
			case "setProperty":
				return "setProperty(" + q(argText(b, 0, "tag", level)) + ", " + v(argText(b, 1, "val", level)) + ")";
			case "getProperty":
				return "getProperty(" + q(argText(b, 0, "tag", level)) + ")";
			case "makeLuaSprite":
				return "makeLuaSprite(" + q(argText(b, 0, "spr", level)) + ", " + q(argText(b, 1, "img", level)) + ", " + v(argText(b, 2, 0, level)) + ", "
					+ v(argText(b, 3, 0, level)) + ")";
			case "makeAnimatedLuaSprite":
				return "makeAnimatedLuaSprite(" + q(argText(b, 0, "spr", level)) + ", " + q(argText(b, 1, "img", level)) + ", " + v(argText(b, 2, 0, level))
					+ ", " + v(argText(b, 3, 0, level)) + ")";
			case "addLuaSprite":
				return "addLuaSprite(" + q(argText(b, 0, "spr", level)) + ", " + v(argText(b, 1, "false", level)) + ")";
			case "scaleObject":
				return "scaleObject("
					+ q(argText(b, 0, "tag", level))
					+ ", "
					+ v(argText(b, 1, 1, level))
					+ ", "
					+ v(argText(b, 2, 1, level))
					+ ")";
			case "setObjectCamera":
				return "setObjectCamera(" + q(argText(b, 0, "tag", level)) + ", " + q(argText(b, 1, "hud", level)) + ")";
			case "screenCenter":
				return "screenCenter(" + q(argText(b, 0, "tag", level)) + ")";

			// Sound
			case "playSound":
				return "playSound(" + q(argText(b, 0, "snd", level)) + ", " + v(argText(b, 1, 1, level)) + ")";
			case "playMusic":
				return "playMusic("
					+ q(argText(b, 0, "snd", level))
					+ ", "
					+ v(argText(b, 1, 1, level))
					+ ", "
					+ v(argText(b, 2, "true", level))
					+ ")";
			case "pauseSound":
				return "pauseSound(" + q(argText(b, 0, "snd", level)) + ")";
			case "stopSound":
				return "stopSound(" + q(argText(b, 0, "snd", level)) + ")";

			// Motion
			case "doTweenX":
				return "doTweenX(" + q(argText(b, 0, "tag", level)) + ", " + q(argText(b, 1, "obj", level)) + ", " + v(argText(b, 2, 100, level)) + ", "
					+ v(argText(b, 3, 1, level)) + ", " + q(argText(b, 4, "linear", level)) + ")";
			case "doTweenY":
				return "doTweenY(" + q(argText(b, 0, "tag", level)) + ", " + q(argText(b, 1, "obj", level)) + ", " + v(argText(b, 2, 100, level)) + ", "
					+ v(argText(b, 3, 1, level)) + ", " + q(argText(b, 4, "linear", level)) + ")";
			case "doTweenAlpha":
				return "doTweenAlpha(" + q(argText(b, 0, "tag", level)) + ", " + q(argText(b, 1, "obj", level)) + ", " + v(argText(b, 2, 1, level)) + ", "
					+ v(argText(b, 3, 1, level)) + ", " + q(argText(b, 4, "linear", level)) + ")";
			case "doTweenZoom":
				return "doTweenZoom(" + q(argText(b, 0, "tag", level)) + ", " + q(argText(b, 1, "game", level)) + ", " + v(argText(b, 2, 1, level)) + ", "
					+ v(argText(b, 3, 1, level)) + ", " + q(argText(b, 4, "linear", level)) + ")";

			// Game
			case "setHealth":
				return "setProperty('health', " + v(argText(b, 0, 1, level)) + ")";
			case "addHealth":
				return "addHealth(" + v(argText(b, 0, 0.1, level)) + ")";
			case "cameraShake":
				return "cameraShake("
					+ q(argText(b, 0, "game", level))
					+ ", "
					+ v(argText(b, 1, 0.05, level))
					+ ", "
					+ v(argText(b, 2, 0.5, level))
					+ ")";
			case "cameraFlash":
				return "cameraFlash("
					+ q(argText(b, 0, "game", level))
					+ ", "
					+ q(argText(b, 1, "FFFFFF", level))
					+ ", "
					+ v(argText(b, 2, 0.5, level))
					+ ")";
			case "cameraFade":
				return "cameraFade("
					+ q(argText(b, 0, "game", level))
					+ ", "
					+ q(argText(b, 1, "000000", level))
					+ ", "
					+ v(argText(b, 2, 0.5, level))
					+ ")";

			// Lua
			case "runLuaCode":
				return reindent(argText(b, 0, "", level), level);
			case "luaExpression":
				return reindent(argText(b, 0, "", level), level);
			case "commentLine":
				return "-- " + v(argText(b, 0, "", level));
			case "callFunction":
				return v(argText(b, 0, "func", level)) + "(" + v(argText(b, 1, "", level)) + ")";
			case "setVariable":
				return v(argText(b, 0, "var", level)) + " = " + v(argText(b, 1, "0", level));
			case "getVariable":
				return v(argText(b, 0, "var", level));
			case "whileTrue":
				return "while true do";
			case "breakLoop":
				return "break";

			default:
				var template:String = strProp(b, LUA_FIELDS);
				if (template != null && template.length > 0)
					return expandTemplate(template, templateArgs(b, level), paramDefs(b));
				return "-- " + labelOf(b);
		}
	}

	// --- Arguments ---

	/** Raw Lua text of argument `index`: a nested reporter resolves to its code. */
	static function argText(b:Block, index:Int, def:Dynamic, level:Int):String
	{
		var raw:Dynamic = inputAt(b, index);
		if (raw == null)
			raw = def;
		if (isBlockValue(raw))
			return codeOf(raw, level);
		if (raw == null || !isPrimitive(raw))
			return "";
		return Std.string(raw);
	}

	/** Every argument of an external block template, already quoted or raw. */
	static function templateArgs(b:Block, level:Int):Array<String>
	{
		var defs:Array<BlockParameter> = paramDefs(b);
		var args:Array<String> = [];

		if (defs.length > 0)
		{
			for (i in 0...defs.length)
				args.push(quotedFor(defs[i].type, argText(b, i, defs[i].defaultValue, level)));
			return args;
		}

		for (i in 0...inputCount(b))
			args.push(q(argText(b, i, null, level)));

		return args;
	}

	static function quotedFor(type:ParamType, resolved:String):String
	{
		if (type == ParamType.NUMBER || type == ParamType.BOOL || type == ParamType.CODE)
			return v(resolved);
		return q(resolved);
	}

	/** Quotes a value unless it is code, a number or a boolean. */
	static function q(val:Dynamic):String
	{
		var text:String = v(val);
		if (text.indexOf("(") != -1 || text == "true" || text == "false" || looksNumeric(text))
			return text;
		return "'" + text + "'";
	}

	/** Leaves a value as it is. */
	static function v(val:Dynamic):String
	{
		if (val == null)
			return "";
		return Std.string(val);
	}

	static function looksNumeric(text:String):Bool
	{
		if (text == null || text.length == 0)
			return false;
		var parsed:Float = Math.NaN;
		try
		{
			parsed = Std.parseFloat(text);
		}
		catch (e:Dynamic)
		{
			return false;
		}
		return !Math.isNaN(parsed);
	}

	static function argByName(name:String, args:Array<String>, params:Array<BlockParameter>):String
	{
		if (name == null || args == null)
			return null;

		if (params != null)
		{
			for (i in 0...params.length)
			{
				if (params[i] == null || params[i].name != name)
					continue;
				if (i < args.length && args[i] != null)
					return args[i];
				return null;
			}
		}

		var index:Null<Int> = Std.parseInt(name);
		if (index != null && index >= 1 && index <= args.length)
			return args[index - 1];
		return null;
	}

	static function escapeSingle(text:String):String
	{
		if (text == null)
			return "";
		return text.split("'").join("\\'");
	}

	/** Re-indents the extra lines of an inline code field to the current level. */
	static function reindent(code:String, level:Int):String
	{
		if (code == null || code.length == 0)
			return "";

		var prefix:String = indent(level);
		var lines:Array<String> = code.split("\n");
		var out:Array<String> = [];

		for (i in 0...lines.length)
		{
			var line:String = stripCarriageReturn(lines[i]);
			if (i == 0 || line.length == 0)
				out.push(line);
			else
				out.push(prefix + line);
		}

		return out.join("\n");
	}

	static function stripCarriageReturn(line:String):String
	{
		if (line == null)
			return "";
		if (line.length > 0 && line.charCodeAt(line.length - 1) == 13)
			return line.substring(0, line.length - 1);
		return line;
	}

	// --- Block structure ---

	static function typeOf(b:Block):String
	{
		if (b == null)
			return "";

		var type:Dynamic = firstField(b, TYPE_FIELDS);
		if (type == null)
		{
			var data:Dynamic = dataOf(b);
			if (data != null && data != b)
				type = firstField(data, TYPE_FIELDS);
		}

		if (type == null)
			return "";
		return Std.string(type);
	}

	/** Label of a block with no generator case; a definition label wins over a display object. */
	static function labelOf(b:Block):String
	{
		var data:Dynamic = dataOf(b);
		var label:String = null;

		if (data != null && data != b)
			label = stringOf(firstField(data, LABEL_FIELDS));
		if (label == null || label.length == 0)
			label = stringOf(firstField(b, LABEL_FIELDS));

		if (label != null && label.length > 0)
			return label;

		var type:String = typeOf(b);
		return (type != null && type.length > 0) ? type : "block";
	}

	static function isHat(b:Block):Bool
	{
		if (b == null)
			return false;

		var flag:Dynamic = prop(b, ["isHat"]);
		if (Std.isOfType(flag, Bool))
			return cast flag;

		var hatLua:String = strProp(b, HAT_FIELDS);
		if (hatLua != null && hatLua.length > 0)
			return true;

		return HAT_TYPES.indexOf(typeOf(b)) != -1;
	}

	static function isOpener(b:Block):Bool
	{
		var type:String = typeOf(b);
		if (OPENER_TYPES.indexOf(type) != -1)
			return true;
		return isHat(b);
	}

	/** Blocks that belong to `b` through a body array rather than through `next`. */
	static function bodyOf(b:Block):Array<Block>
	{
		var raw:Dynamic = prop(b, BODY_FIELDS);
		if (raw == null || !Std.isOfType(raw, Array))
			return null;

		var body:Array<Block> = [];
		for (item in (cast raw : Array<Dynamic>))
		{
			if (item == null)
				continue;
			var block:Block = item;
			if (block == b)
				continue;
			body.push(block);
		}

		return body.length > 0 ? body : null;
	}

	static function nextOf(b:Block):Block
	{
		if (b == null)
			return null;

		var raw:Dynamic = firstField(b, NEXT_FIELDS);
		if (raw == null || isPrimitive(raw) || Std.isOfType(raw, Array))
			return null;
		return raw;
	}

	static function inputAt(b:Block, index:Int):Dynamic
	{
		if (b == null || index < 0)
			return null;

		var container:Dynamic = inputContainer(b);
		if (container == null)
			return null;

		if (Std.isOfType(container, Array))
		{
			var list:Array<Dynamic> = cast container;

			for (item in list)
			{
				if (item == null || isPrimitive(item) || Std.isOfType(item, Array))
					continue;
				var itemIndex:Null<Int> = toInt(Reflect.field(item, "index"));
				if (itemIndex == null || itemIndex != index)
					continue;
				if (!hasFieldSafe(item, "value"))
					continue;
				return unwrapInput(Reflect.field(item, "value"));
			}

			if (index < list.length)
				return unwrapInput(list[index]);
			return null;
		}

		var named:Dynamic = lookupKey(container, paramName(b, index));
		if (named != null)
			return unwrapInput(named);

		return unwrapInput(lookupKey(container, Std.string(index)));
	}

	static function inputContainer(b:Block):Dynamic
	{
		if (b == null)
			return null;

		var raw:Dynamic = firstField(b, INPUT_FIELDS);
		if (raw == null)
		{
			var data:Dynamic = dataOf(b);
			if (data != null && data != b)
				raw = firstField(data, INPUT_FIELDS);
		}

		return raw;
	}

	static function inputCount(b:Block):Int
	{
		var container:Dynamic = inputContainer(b);
		if (container == null)
			return 0;
		if (Std.isOfType(container, Array))
			return (cast container : Array<Dynamic>).length;

		var defs:Array<BlockParameter> = paramDefs(b);
		return defs.length;
	}

	/** Unwraps `{index, value}` / `InputField` style entries to the value or reporter. */
	static function unwrapInput(item:Dynamic):Dynamic
	{
		if (item == null || isPrimitive(item) || Std.isOfType(item, Array))
			return item;

		var attached:Dynamic = Reflect.field(item, "attachedBlock");
		if (attached != null)
			return attached;

		var value:Dynamic = Reflect.field(item, "value");
		if (value != null && isPrimitive(value))
			return value;
		if (value != null && isBlockValue(value))
			return value;
		if (hasFieldSafe(item, "attachedBlock") || hasFieldSafe(item, "parentBlock") || hasFieldSafe(item, "placeholder"))
			return value;

		return item;
	}

	static function isBlockValue(value:Dynamic):Bool
	{
		if (value == null || isPrimitive(value) || Std.isOfType(value, Array))
			return false;
		if (Std.isOfType(value, Block))
			return true;
		if (hasFieldSafe(value, "blockType") || hasFieldSafe(value, "blockData") || hasFieldSafe(value, "hatLua"))
			return true;

		var type:Dynamic = Reflect.field(value, "type");
		if (!Std.isOfType(type, String))
			return false;
		return !isParamTypeName(Std.string(type));
	}

	static function paramDefs(b:Block):Array<BlockParameter>
	{
		var defs:Array<BlockParameter> = [];
		if (b == null)
			return defs;

		var raw:Dynamic = prop(b, PARAM_DEF_FIELDS);
		if (raw == null)
			raw = prop(b, INPUT_FIELDS);
		if (raw == null || !Std.isOfType(raw, Array))
			return defs;

		for (item in (cast raw : Array<Dynamic>))
		{
			if (item == null || isPrimitive(item) || Std.isOfType(item, Array))
				continue;

			var name:Dynamic = Reflect.field(item, "name");
			var type:Dynamic = Reflect.field(item, "type");
			if (!Std.isOfType(name, String) || !Std.isOfType(type, String))
				continue;
			if (!hasFieldSafe(item, "defaultValue") && !hasFieldSafe(item, "options") && !isParamTypeName(Std.string(type)))
				continue;

			defs.push({
				name: Std.string(name),
				type: Std.string(type),
				defaultValue: Reflect.field(item, "defaultValue")
			});
		}

		return defs;
	}

	static function paramName(b:Block, index:Int):String
	{
		var defs:Array<BlockParameter> = paramDefs(b);
		if (index < 0 || index >= defs.length)
			return null;

		var name:String = defs[index].name;
		return (name != null && name.length > 0) ? name : null;
	}

	static function isParamTypeName(name:String):Bool
	{
		if (name == null)
			return false;

		for (type in [
			ParamType.STRING,
			ParamType.NUMBER,
			ParamType.BOOL,
			ParamType.CODE,
			ParamType.COLOR,
			ParamType.SELECT
		])
		{
			if (name == type)
				return true;
		}

		return false;
	}

	// --- Field access ---

	static function dataOf(b:Block):Dynamic
	{
		var data:Dynamic = firstField(b, DATA_FIELDS);
		if (data == null || isPrimitive(data) || Std.isOfType(data, Array))
			return null;

		if (firstField(data, TYPE_FIELDS) == null
			&& firstField(data, LABEL_FIELDS) == null
			&& firstField(data, HAT_FIELDS) == null
			&& firstField(data, LUA_FIELDS) == null
			&& firstField(data, PARAM_DEF_FIELDS) == null)
		{
			return null;
		}

		return data;
	}

	static function prop(b:Block, names:Array<String>):Dynamic
	{
		if (b == null)
			return null;

		var value:Dynamic = firstField(b, names);
		if (value != null)
			return value;

		var data:Dynamic = dataOf(b);
		if (data != null && data != b)
			return firstField(data, names);

		return null;
	}

	static function strProp(b:Block, names:Array<String>):String
	{
		return stringOf(prop(b, names));
	}

	/** Text held by a field, and nothing when the field holds a display object or the like. */
	static function stringOf(value:Dynamic):String
	{
		if (value == null)
			return null;
		if (Std.isOfType(value, String))
			return cast value;
		if (isPrimitive(value))
			return Std.string(value);
		return null;
	}

	static function firstField(obj:Dynamic, names:Array<String>):Dynamic
	{
		if (obj == null || isPrimitive(obj) || Std.isOfType(obj, Array))
			return null;

		for (name in names)
		{
			// Never gate this on `Reflect.hasField()`: on hxcpp it reports false for fields that
			// are *declared* on a class (`Block.blockData`, `Block.nextBlock`, the `InputField`s),
			// which made every lookup here miss and compiled every block to a `-- block` comment.
			var value:Dynamic = readField(obj, name);
			if (value != null)
				return value;
		}

		return null;
	}

	/** Reads a field and returns null instead of throwing when it does not exist. */
	static function readField(obj:Dynamic, name:String):Dynamic
	{
		if (obj == null || name == null || isPrimitive(obj) || Std.isOfType(obj, Array))
			return null;

		try
		{
			return Reflect.field(obj, name);
		}
		catch (e:Dynamic)
		{
			return null;
		}
	}

	/** Target-safe field existence test; `readField()` has the same semantics everywhere. */
	static function hasFieldSafe(obj:Dynamic, name:String):Bool
	{
		if (obj == null || isPrimitive(obj) || Std.isOfType(obj, Array))
			return false;
		if (Reflect.hasField(obj, name))
			return true;

		return readField(obj, name) != null;
	}

	static function lookupKey(container:Dynamic, key:String):Dynamic
	{
		if (container == null || isPrimitive(container) || key == null || key.length == 0)
			return null;

		if (hasFieldSafe(container, key))
		{
			var value:Dynamic = readField(container, key);
			if (value != null)
				return value;
		}

		try
		{
			var getter:Dynamic = Reflect.field(container, "get");
			if (getter != null)
				return Reflect.callMethod(container, getter, [key]);
		}
		catch (e:Dynamic)
		{
			return null;
		}

		return null;
	}

	static function markerStep(marker:TimelineMarker):Null<Int>
	{
		return toInt(Reflect.field(marker, "step"));
	}

	static function markerEventName(marker:TimelineMarker):String
	{
		var raw:Dynamic = Reflect.field(marker, "eventName");
		if (raw == null)
			return null;
		var name:String = Std.string(raw);
		return name.length > 0 ? name : null;
	}

	static function toInt(value:Dynamic):Null<Int>
	{
		if (value == null)
			return null;
		if (Std.isOfType(value, Int) || Std.isOfType(value, Float))
			return Std.int(cast value);
		return Std.parseInt(Std.string(value));
	}

	static function isPrimitive(value:Dynamic):Bool
	{
		if (value == null)
			return true;
		if (Std.isOfType(value, String))
			return true;
		if (Std.isOfType(value, Float) || Std.isOfType(value, Int))
			return true;
		if (Std.isOfType(value, Bool))
			return true;
		return false;
	}
}
