package editors.blockcode;

import editors.blockcode.BlockTypes.BlockData;
import editors.blockcode.BlockTypes.BlockParameter;
import editors.blockcode.BlockTypes.ImportResult;
import editors.blockcode.BlockTypes.ParamType;
import editors.blockcode.BlockTypes.TimelineEntry;
import editors.blockcode.BlockTypes.TimelineMarker;

using StringTools;

/**
 * Turns an existing Lua script back into block-code nodes, the inverse of the
 * block Lua generator.
 *
 * The parser understands a Lua subset: line comments, `--[[ ]]` block comments,
 * long strings, short strings with escapes, numbers, identifiers and the usual
 * punctuation. Anything it cannot map onto a block is kept verbatim inside a
 * raw-Lua block and reported through `ImportResult.warnings`; `importCode()`
 * never throws.
 */
class BlockLuaImporter
{
	/** Workspace grid. Every generated position is a multiple of this value. */
	public static inline var GRID_SIZE:Int = 40;

	/** Top-left corner the first stack is placed at. */
	public static inline var BASE_X:Float = 360;

	public static inline var BASE_Y:Float = 200;

	/** Stacks per row before the next row starts. */
	public static inline var STACK_COLUMNS:Int = 3;

	public static inline var STACK_COLUMN_STEP:Float = 560;
	public static inline var STACK_ROW_STEP:Float = 600;

	/** Distance between two blocks of the same stack. */
	public static inline var STACK_CHAIN_STEP:Float = 50;

	public static inline var MAX_WARNINGS:Int = 80;

	/** Top level functions that become hat blocks. */
	public static var HAT_FUNCTIONS:Array<String> = [
		"onCreate",
		"onCreatePost",
		"onUpdate",
		"onUpdatePost",
		"onBeatHit",
		"onStepHit",
		"onDestroy",
		"onEvent"
	];

	/**
	 * Converts `code` into blocks.
	 *
	 * Haxe reserves `import` as a keyword, so the documented entry point is
	 * spelled `importCode` (with `importLua` as an alias for callers that use
	 * the other spelling).
	 */
	public static function importCode(code:String):ImportResult
	{
		var importer:LuaImporter = new LuaImporter(code == null ? "" : code);
		return importer.run();
	}

	public static function importLua(code:String):ImportResult
	{
		return importCode(code);
	}

	/** True when the script carries the header the block editor writes. */
	public static function looksLikeGenerated(code:String):Bool
	{
		if (code == null)
			return false;

		var lines:Array<String> = code.split("\n");
		var limit:Int = Std.int(Math.min(lines.length, 8));

		for (i in 0...limit)
		{
			var trimmed:String = lines[i].trim();
			if (trimmed.length == 0)
				continue;
			if (!trimmed.startsWith("--"))
				break;
			if (trimmed.toLowerCase().indexOf("generated by") != -1)
				return true;
			if (trimmed.startsWith("--[") && trimmed.indexOf("[", 3) != -1)
			{
				// The header may be written as a long comment, so read the whole block.
				return lines.slice(i, limit).join("\n").toLowerCase().indexOf("generated by") != -1;
			}
		}
		return false;
	}

	/** Block definition lookup, null when the library does not know `type`. */
	public static function getBlockData(type:String):BlockData
	{
		if (type == null || type.length == 0)
			return null;
		return BlockLibrary.get(type);
	}

	/** Arity of a known block, or -1 when it is unknown. */
	public static function knownArity(type:String):Int
	{
		var data:BlockData = getBlockData(type);
		if (data != null && data.parameters != null)
			return data.parameters.length;

		return switch (type)
		{
			case "close", "curStep", "curBeat", "songPosition", "health", "getSongPosition", "breakLoop", "else", "end", "whileTrue", "callFunction",
				"onCreate", "onCreatePost", "onUpdate", "onUpdatePost", "onBeatHit", "onStepHit", "onDestroy": 0;
			case "debugPrint", "addHealth", "pauseSound", "stopSound", "screenCenter", "keyJustPressed", "keyPressed", "getProperty", "not", "wait",
				"runLuaCode": 1;
			case "setProperty", "addLuaSprite", "playSound", "add", "sub", "mul", "div", "eq", "gt", "lt", "and", "or", "join", "setVariable": 2;
			case "cameraShake", "cameraFlash", "cameraFade", "scaleObject", "playMusic", "getPixelColor": 3;
			case "makeLuaSprite", "makeAnimatedLuaSprite": 4;
			case "doTweenX", "doTweenY", "doTweenAlpha", "doTweenZoom": 5;
			default: -1;
		}
	}
}

/** A top level `function name(params) ... end`. */
private typedef FuncDef =
{
	var name:String;
	var params:Array<String>;
	var body:Array<PStmt>;
	var raw:String;
	var line:Int;
}

private enum TokenKind
{
	TkName;
	TkNumber;
	TkString;
	TkSymbol;
	TkEof;
}

private typedef Token =
{
	var kind:TokenKind;

	/** Raw source text; strings keep their quotes. */
	var text:String;

	/** Decoded value of a string literal, otherwise the same as `text`. */
	var value:String;

	var line:Int;
	var start:Int;
	var finish:Int;
}

private typedef PIfBranch =
{
	var cond:Expr;
	var body:Array<PStmt>;
}

private enum PStmt
{
	PCall(name:String, args:Array<Expr>, raw:String, line:Int);
	PAssign(target:String, value:Expr, raw:String, line:Int);
	PIf(cond:Expr, body:Array<PStmt>, elseifs:Array<PIfBranch>, elseBody:Array<PStmt>, raw:String, line:Int);
	PWhile(cond:Expr, body:Array<PStmt>, raw:String, line:Int);
	PBreak(raw:String, line:Int);
	PRaw(text:String, line:Int);
}

private enum Expr
{
	ENumber(raw:String, value:Float);
	EString(raw:String, value:String);
	EBool(raw:String, value:Bool);
	EIdent(raw:String);
	EField(raw:String, target:Expr, name:String);
	EIndex(raw:String, target:Expr, index:Expr);
	ECall(raw:String, name:String, args:Array<Expr>);
	EBinop(raw:String, op:String, left:Expr, right:Expr);
	EUnop(raw:String, op:String, operand:Expr);
	EGroup(raw:String, inner:Expr);
	ERaw(raw:String);
}

class LuaImporter
{
	static var STATEMENT_CALLS:Array<String> = [
		"debugPrint",
		"addHealth",
		"cameraShake",
		"cameraFlash",
		"cameraFade",
		"playSound",
		"playMusic",
		"pauseSound",
		"stopSound",
		"doTweenX",
		"doTweenY",
		"doTweenAlpha",
		"doTweenZoom",
		"makeLuaSprite",
		"makeAnimatedLuaSprite",
		"addLuaSprite",
		"scaleObject",
		"setObjectCamera",
		"screenCenter"
	];

	static var REPORTER_CALLS:Array<String> = [
		"keyJustPressed",
		"keyPressed",
		"getPixelColor",
		"getProperty",
		"add",
		"sub",
		"mul",
		"div",
		"eq",
		"gt",
		"lt",
		"and",
		"or",
		"not",
		"join"
	];

	static var KEYWORDS:Array<String> = [
		"and",
		"break",
		"do",
		"else",
		"elseif",
		"end",
		"false",
		"for",
		"function",
		"if",
		"in",
		"local",
		"nil",
		"not",
		"or",
		"repeat",
		"return",
		"then",
		"true",
		"until",
		"while"
	];

	static var STATEMENT_STOPS:Array<String> = ["end", "else", "elseif", "until", "then"];

	/** Names whose generated code differs from the name itself, so a bare identifier must stay text. */
	static var IDENT_EXCEPTIONS:Array<String> = ["health", "songPosition", "getProperty", "getSongPosition"];

	var src:String;
	var tokens:Array<Token> = [];
	var pos:Int = 0;
	var warnings:Array<String> = [];
	var stacks:Array<Dynamic> = [];
	var timeline:Array<TimelineEntry> = [];

	public function new(code:String)
	{
		src = code;
	}

	public function run():ImportResult
	{
		try
		{
			tokenize();
		}
		catch (e:Dynamic)
		{
			warn(0, "Tokenizing stopped early: " + Std.string(e));
		}

		tokens.push({
			kind: TkEof,
			text: "",
			value: "",
			line: src.length > 0 ? src.split("\n").length : 1,
			start: src.length,
			finish: src.length
		});

		try
		{
			parseTopLevel();
		}
		catch (e:Dynamic)
		{
			warn(0, "Import stopped early: " + Std.string(e));
		}

		try
		{
			layoutAll();
		}
		catch (e:Dynamic)
		{
			warn(0, "Some blocks could not be positioned on the workspace grid.");
		}

		return {
			stacks: stacks,
			timeline: timeline,
			settings: BlockTypes.defaultSettings(),
			warnings: warnings
		};
	}

	// --- Tokenizer ---

	function tokenize():Void
	{
		var i:Int = 0;
		var line:Int = 1;
		var n:Int = src.length;

		while (i < n)
		{
			var c:String = src.charAt(i);

			if (c == "\n")
			{
				line++;
				i++;
				continue;
			}
			if (isWhitespace(c))
			{
				i++;
				continue;
			}

			if (c == "-" && i + 1 < n && src.charAt(i + 1) == "-")
			{
				var level:Int = longBracketLevel(i + 2);
				if (level >= 0)
				{
					var closer:String = "]" + repeatChar("=", level) + "]";
					var close:Int = src.indexOf(closer, i + 2);
					if (close < 0)
					{
						warn(line, "Unterminated block comment");
						i = n;
					}
					else
					{
						line += countLines(src.substring(i, close));
						i = close + closer.length;
					}
				}
				else
				{
					var newline:Int = src.indexOf("\n", i);
					i = (newline < 0) ? n : newline;
				}
				continue;
			}

			if (c == "[")
			{
				var level:Int = longBracketLevel(i);
				if (level >= 0)
				{
					var startLine:Int = line;
					var opener:String = "[" + repeatChar("=", level) + "[";
					var closer:String = "]" + repeatChar("=", level) + "]";
					var body:Int = i + opener.length;
					var close:Int = src.indexOf(closer, body);
					var finish:Int = (close < 0) ? n : close + closer.length;
					var value:String = src.substring(body, (close < 0) ? n : close);
					if (value.startsWith("\n"))
						value = value.substr(1);
					if (close < 0)
						warn(startLine, "Unterminated long string");
					line += countLines(src.substring(i, finish));
					pushToken(TkString, src.substring(i, finish), value, startLine, i, finish);
					i = finish;
				}
				else
				{
					pushToken(TkSymbol, c, c, line, i, i + 1);
					i++;
				}
				continue;
			}

			if (c == "\"" || c == "'")
			{
				var startLine:Int = line;
				var start:Int = i;
				var quote:String = c;
				var value:String = "";
				var closed:Bool = false;
				i++;

				while (i < n)
				{
					var ch:String = src.charAt(i);

					if (ch == "\\")
					{
						i++;
						if (i >= n)
							break;
						var esc:String = src.charAt(i);
						if (esc == "n")
						{
							value += "\n";
							i++;
						}
						else if (esc == "t")
						{
							value += "\t";
							i++;
						}
						else if (esc == "r")
						{
							value += "\r";
							i++;
						}
						else if (esc == "a")
						{
							value += String.fromCharCode(7);
							i++;
						}
						else if (esc == "b")
						{
							value += String.fromCharCode(8);
							i++;
						}
						else if (esc == "f")
						{
							value += String.fromCharCode(12);
							i++;
						}
						else if (esc == "v")
						{
							value += String.fromCharCode(11);
							i++;
						}
						else if (esc == "\\" || esc == "\"" || esc == "'")
						{
							value += esc;
							i++;
						}
						else if (esc == "\n")
						{
							value += "\n";
							line++;
							i++;
						}
						else if (esc == "x")
						{
							i++;
							var hex:String = src.substr(i, 2);
							var code:Null<Int> = Std.parseInt("0x" + hex);
							if (code == null)
							{
								warn(startLine, "Invalid hexadecimal escape sequence");
								i += hex.length;
							}
							else
							{
								value += String.fromCharCode(code);
								i += 2;
							}
						}
						else if (esc == "z")
						{
							i++;
							while (i < n && isWhitespace(src.charAt(i)))
							{
								if (src.charAt(i) == "\n")
									line++;
								i++;
							}
						}
						else if (esc >= "0" && esc <= "9")
						{
							var digits:String = "";
							while (digits.length < 3 && i < n && src.charAt(i) >= "0" && src.charAt(i) <= "9")
							{
								digits += src.charAt(i);
								i++;
							}
							var code2:Null<Int> = Std.parseInt(digits);
							value += String.fromCharCode(code2 == null ? 0 : code2);
						}
						else
						{
							warn(startLine, "Unknown escape sequence '\\" + esc + "'");
							value += esc;
							i++;
						}
						continue;
					}

					if (ch == quote)
					{
						closed = true;
						i++;
						break;
					}
					if (ch == "\n")
						line++;
					value += ch;
					i++;
				}

				if (!closed)
					warn(startLine, "Unterminated string literal");
				pushToken(TkString, src.substring(start, i), value, startLine, start, i);
				continue;
			}

			if (isDigit(c) || (c == "." && isDigit(src.charAt(i + 1))))
			{
				var start:Int = i;
				if (c == "0" && (src.charAt(i + 1) == "x" || src.charAt(i + 1) == "X"))
				{
					i += 2;
					while (i < n && isHexDigit(src.charAt(i)))
						i++;
				}
				else
				{
					while (i < n && isDigit(src.charAt(i)))
						i++;
					if (src.charAt(i) == ".")
					{
						i++;
						while (i < n && isDigit(src.charAt(i)))
							i++;
					}
					if (src.charAt(i) == "e" || src.charAt(i) == "E")
					{
						var look:Int = i + 1;
						if (src.charAt(look) == "+" || src.charAt(look) == "-")
							look++;
						if (isDigit(src.charAt(look)))
						{
							i = look;
							while (i < n && isDigit(src.charAt(i)))
								i++;
						}
					}
				}
				pushToken(TkNumber, src.substring(start, i), src.substring(start, i), line, start, i);
				continue;
			}

			if (isIdentStart(c))
			{
				var start:Int = i;
				while (i < n && isIdentChar(src.charAt(i)))
					i++;
				pushToken(TkName, src.substring(start, i), src.substring(start, i), line, start, i);
				continue;
			}

			var three:String = src.substr(i, 3);
			var two:String = src.substr(i, 2);
			if (three == "...")
			{
				pushToken(TkSymbol, three, three, line, i, i + 3);
				i += 3;
				continue;
			}
			if (two == ".." || two == "==" || two == "~=" || two == "<=" || two == ">=" || two == "::" || two == "//")
			{
				pushToken(TkSymbol, two, two, line, i, i + 2);
				i += 2;
				continue;
			}

			pushToken(TkSymbol, c, c, line, i, i + 1);
			i++;
		}
	}

	function pushToken(kind:TokenKind, text:String, value:String, line:Int, start:Int, finish:Int):Void
	{
		tokens.push({
			kind: kind,
			text: text,
			value: value,
			line: line,
			start: start,
			finish: finish
		});
	}

	function longBracketLevel(index:Int):Int
	{
		if (index >= src.length || src.charAt(index) != "[")
			return -1;

		var i:Int = index + 1;
		var level:Int = 0;
		while (i < src.length && src.charAt(i) == "=")
		{
			level++;
			i++;
		}
		return (i < src.length && src.charAt(i) == "[") ? level : -1;
	}

	// --- Parser ---

	function parseTopLevel():Void
	{
		var pending:Array<Dynamic> = [];

		while (peek().kind != TkEof)
		{
			if (isSymbol(peek(), ";"))
			{
				pos++;
				continue;
			}

			if (isName(peek(), "function"))
			{
				flushPending(pending);
				handleFunction(parseFunction());
				continue;
			}
			if (isName(peek(), "local") && isName(peekAt(1), "function"))
			{
				flushPending(pending);
				warn(peek().line, "A local function cannot become a hat block, it was imported as raw Lua code");
				var start:Int = peek().start;
				consumeRawStatement();
				pending.push(runLuaCodeNode(src.substring(start, lastFinish())));
				continue;
			}

			var before:Int = pos;
			var stmt:PStmt = parseStatement();
			if (stmt != null)
				stmtToNodes(stmt, pending);
			if (pos == before)
				pos++;
		}

		flushPending(pending);
	}

	function flushPending(pending:Array<Dynamic>):Void
	{
		if (pending.length == 0)
			return;
		var root:Dynamic = chainNodes(pending);
		if (root != null)
			stacks.push(root);
		pending.splice(0, pending.length);
	}

	function parseFunction():FuncDef
	{
		var startToken:Token = peek();
		pos++;

		var name:String = "";
		if (peek().kind == TkName)
		{
			name = peek().text;
			pos++;
		}
		while (isSymbol(peek(), ".") || isSymbol(peek(), ":"))
		{
			var sep:String = peek().text;
			pos++;
			if (peek().kind == TkName)
			{
				name += sep + peek().text;
				pos++;
			}
		}

		var params:Array<String> = [];
		if (isSymbol(peek(), "("))
		{
			pos++;
			while (peek().kind != TkEof && !isSymbol(peek(), ")"))
			{
				if (peek().kind == TkName)
				{
					params.push(peek().text);
					pos++;
				}
				else if (isSymbol(peek(), ","))
				{
					pos++;
				}
				else
				{
					pos++;
				}
			}
			if (isSymbol(peek(), ")"))
				pos++;
		}

		var body:Array<PStmt> = parseChunk(["end"]);
		if (isName(peek(), "end"))
			pos++;
		else
			warn(startToken.line, "function " + (name.length > 0 ? name : "?") + " is missing its closing 'end'");

		return {
			name: name,
			params: params,
			body: body,
			raw: src.substring(startToken.start, lastFinish()),
			line: startToken.line
		};
	}

	function handleFunction(fn:FuncDef):Void
	{
		if (!BlockLuaImporter.HAT_FUNCTIONS.contains(fn.name))
		{
			warn(fn.line, "Unknown function '" + fn.name + "' was imported as raw Lua code");
			stacks.push(chainNodes([runLuaCodeNode(fn.raw)]));
			return;
		}

		if (fn.name == "onStepHit")
		{
			var stepEntries:Array<TimelineEntry> = extractStepTimeline(fn);
			if (stepEntries != null)
			{
				for (entry in stepEntries)
					timeline.push(entry);
				return;
			}
		}
		else if (fn.name == "onEvent")
		{
			var guard:String = fn.params.length > 0 ? fn.params[0] : "n";
			var eventEntries:Array<TimelineEntry> = extractEventTimeline(fn, guard);
			if (eventEntries != null)
			{
				for (entry in eventEntries)
					timeline.push(entry);
				return;
			}
		}

		var nodes:Array<Dynamic> = [];
		for (stmt in fn.body)
			stmtToNodes(stmt, nodes);

		var hat:Dynamic = makeNode(fn.name);
		fillHatInputs(hat, fn);
		hat.next = chainNodes(nodes);
		stacks.push(hat);
	}

	function fillHatInputs(hat:Dynamic, fn:FuncDef):Void
	{
		var data:BlockData = BlockLuaImporter.getBlockData(fn.name);
		if (data == null || data.parameters == null)
			return;

		var count:Int = Std.int(Math.min(data.parameters.length, fn.params.length));
		for (i in 0...count)
			hat.inputs.push({index: i, value: fn.params[i]});
	}

	function extractStepTimeline(fn:FuncDef):Array<TimelineEntry>
	{
		if (fn.body.length == 0)
			return null;

		var out:Array<TimelineEntry> = [];
		for (stmt in fn.body)
		{
			switch (stmt)
			{
				case PIf(cond, body, elseifs, elseBody, _, _):
					if (elseifs.length > 0 || elseBody != null)
						return null;
					var step:Null<Int> = matchStepGuard(cond, "curStep");
					if (step == null)
						return null;
					var nodes:Array<Dynamic> = [];
					for (inner in body)
						stmtToNodes(inner, nodes);
					out.push(makeEntry("step_" + step, step, "Step " + step, null, chainNodes(nodes)));
				default:
					return null;
			}
		}
		return out;
	}

	function extractEventTimeline(fn:FuncDef, guard:String):Array<TimelineEntry>
	{
		if (fn.body.length == 0)
			return null;

		var out:Array<TimelineEntry> = [];
		for (stmt in fn.body)
		{
			switch (stmt)
			{
				case PIf(cond, body, elseifs, elseBody, _, _):
					if (elseifs.length > 0 || elseBody != null)
						return null;
					var eventName:Null<String> = matchEventGuard(cond, guard);
					if (eventName == null)
						return null;
					var nodes:Array<Dynamic> = [];
					for (inner in body)
						stmtToNodes(inner, nodes);
					out.push(makeEntry("event_" + eventName, 0, eventName, eventName, chainNodes(nodes)));
				default:
					return null;
			}
		}
		return out;
	}

	function makeEntry(id:String, step:Int, name:String, eventName:String, stack:Dynamic):TimelineEntry
	{
		var marker:TimelineMarker = {
			id: id,
			step: step,
			time: 0,
			name: name,
			locked: false
		};
		if (eventName != null)
			marker.eventName = eventName;
		return {marker: marker, stack: stack};
	}

	function matchStepGuard(cond:Expr, guard:String):Null<Int>
	{
		var clean:Expr = stripGroups(cond);
		return switch (clean)
		{
			case EBinop(_, "==", a, b): stepFromPair(a, b, guard);
			default: null;
		}
	}

	function stepFromPair(a:Expr, b:Expr, guard:String):Null<Int>
	{
		var left:Expr = stripGroups(a);
		var right:Expr = stripGroups(b);
		if (isGuardIdent(left, guard) && isNumber(right))
			return intOf(right);
		if (isGuardIdent(right, guard) && isNumber(left))
			return intOf(left);
		return null;
	}

	function matchEventGuard(cond:Expr, guard:String):Null<String>
	{
		var clean:Expr = stripGroups(cond);
		return switch (clean)
		{
			case EBinop(_, "==", a, b): eventFromPair(a, b, guard);
			default: null;
		}
	}

	function eventFromPair(a:Expr, b:Expr, guard:String):Null<String>
	{
		var left:Expr = stripGroups(a);
		var right:Expr = stripGroups(b);
		if (isGuardIdent(left, guard) && isString(right))
			return stringOf(right);
		if (isGuardIdent(right, guard) && isString(left))
			return stringOf(left);
		return null;
	}

	function isGuardIdent(e:Expr, guard:String):Bool
	{
		return switch (e)
		{
			case EIdent(name): name == guard;
			default: false;
		}
	}

	function isNumber(e:Expr):Bool
	{
		return switch (e)
		{
			case ENumber(_, _): true;
			default: false;
		}
	}

	function isString(e:Expr):Bool
	{
		return switch (e)
		{
			case EString(_, _): true;
			default: false;
		}
	}

	function intOf(e:Expr):Null<Int>
	{
		return switch (e)
		{
			case ENumber(_, value):
				var rounded:Int = Std.int(value);
				(rounded == value) ? rounded : null;
			default: null;
		}
	}

	function stringOf(e:Expr):Null<String>
	{
		return switch (e)
		{
			case EString(_, value): value;
			default: null;
		}
	}

	function parseChunk(stops:Array<String>):Array<PStmt>
	{
		var out:Array<PStmt> = [];
		while (peek().kind != TkEof)
		{
			var t:Token = peek();
			if (t.kind == TkName && stops.indexOf(t.text) != -1)
				break;

			var before:Int = pos;
			var stmt:PStmt = parseStatement();
			if (stmt != null)
				out.push(stmt);
			if (pos == before)
				pos++;
		}
		return out;
	}

	function parseStatement():PStmt
	{
		var t:Token = peek();

		if (isSymbol(t, ";"))
		{
			pos++;
			return null;
		}

		if (t.kind == TkName)
		{
			switch (t.text)
			{
				case "if":
					return parseIf();
				case "while":
					return parseWhile();
				case "break":
					pos++;
					consumeSemicolon();
					return PBreak(src.substring(t.start, lastFinish()), t.line);
				case "function", "for", "repeat", "do", "local", "return", "goto":
					pos++;
					return parseRawStatement(t.line, "'" + t.text + "' is not supported by the block editor");
				case "end", "else", "elseif", "until", "then":
					pos++;
					warn(t.line, "Unexpected '" + t.text + "'");
					return null;
			}
		}

		return parseSimpleStatement();
	}

	function parseRawStatement(line:Int, reason:String):PStmt
	{
		var start:Int = pos > 0 ? tokens[pos - 1].start : 0;
		consumeRawStatement();
		warn(line, reason + ", it was imported as raw Lua code");
		return PRaw(src.substring(start, lastFinish()), line);
	}

	function parseIf():PStmt
	{
		var startToken:Token = peek();
		pos++;

		var cond:Expr = parseExpr();
		expectName("then");
		var body:Array<PStmt> = parseChunk(["end", "elseif", "else"]);

		var elseifs:Array<PIfBranch> = [];
		var elseBody:Array<PStmt> = null;

		while (isName(peek(), "elseif"))
		{
			pos++;
			var branchCond:Expr = parseExpr();
			expectName("then");
			elseifs.push({cond: branchCond, body: parseChunk(["end", "elseif", "else"])});
		}

		if (isName(peek(), "else"))
		{
			pos++;
			elseBody = parseChunk(["end"]);
		}

		if (isName(peek(), "end"))
			pos++;
		else
			warn(startToken.line, "'if' is missing its closing 'end'");

		return PIf(cond, body, elseifs, elseBody, src.substring(startToken.start, lastFinish()), startToken.line);
	}

	function parseWhile():PStmt
	{
		var startToken:Token = peek();
		pos++;

		var cond:Expr = parseExpr();
		if (isName(peek(), "do"))
			pos++;
		else
			warn(startToken.line, "'while' is missing its 'do'");

		var body:Array<PStmt> = parseChunk(["end"]);
		if (isName(peek(), "end"))
			pos++;
		else
			warn(startToken.line, "'while' is missing its closing 'end'");

		return PWhile(cond, body, src.substring(startToken.start, lastFinish()), startToken.line);
	}

	function parseSimpleStatement():PStmt
	{
		var startToken:Token = peek();
		var line:Int = startToken.line;

		if (startToken.kind != TkName)
		{
			warn(line, "Unexpected token '" + shorten(startToken.text) + "'");
			skipToLineEnd();
			return PRaw(src.substring(startToken.start, lastFinish()), line);
		}

		var target:String = startToken.text;
		pos++;

		var methodCall:Bool = false;
		while (isSymbol(peek(), ".") || isSymbol(peek(), "[") || isSymbol(peek(), ":"))
		{
			if (isSymbol(peek(), ":"))
			{
				methodCall = true;
				pos++;
				if (peek().kind == TkName)
				{
					target += ":" + peek().text;
					pos++;
				}
			}
			else if (isSymbol(peek(), "."))
			{
				pos++;
				if (peek().kind == TkName)
				{
					target += "." + peek().text;
					pos++;
				}
				else
					warn(line, "Expected a field name after '.'");
			}
			else
			{
				pos++;
				var index:Expr = parseExpr();
				target += "[" + rawOf(index) + "]";
				if (isSymbol(peek(), "]"))
					pos++;
				else
					warn(line, "Expected ']'");
			}
		}

		if (isSymbol(peek(), "("))
		{
			pos++;
			var args:Array<Expr> = parseArgList();
			consumeSemicolon();
			var raw:String = src.substring(startToken.start, lastFinish());
			if (methodCall)
			{
				warn(line, "Method call '" + target + "(...)' was imported as raw Lua code");
				return PRaw(raw, line);
			}
			if (!atStatementEnd())
			{
				warn(line, "Unexpected token '" + shorten(peek().text) + "' after '" + target + "(...)'");
				skipToLineEnd();
				return PRaw(src.substring(startToken.start, lastFinish()), line);
			}
			return PCall(target, args, raw, line);
		}

		if (isSymbol(peek(), "=") && !methodCall)
		{
			pos++;
			var value:Expr = parseExpr();
			consumeSemicolon();
			var raw:String = src.substring(startToken.start, lastFinish());
			if (!atStatementEnd())
			{
				warn(line, "Unexpected token '" + shorten(peek().text) + "' after the assignment to '" + target + "'");
				skipToLineEnd();
				return PRaw(src.substring(startToken.start, lastFinish()), line);
			}
			return PAssign(target, value, raw, line);
		}

		if (isSymbol(peek(), ",") || isSymbol(peek(), "="))
		{
			warn(line, "Multiple assignment is not supported by the block editor, it was imported as raw Lua code");
			skipToLineEnd();
			return PRaw(src.substring(startToken.start, lastFinish()), line);
		}

		warn(line, "Statement '" + shorten(target) + "' was imported as raw Lua code");
		skipToLineEnd();
		return PRaw(src.substring(startToken.start, lastFinish()), line);
	}

	function parseArgList():Array<Expr>
	{
		var args:Array<Expr> = [];
		while (peek().kind != TkEof)
		{
			if (isSymbol(peek(), ")"))
			{
				pos++;
				break;
			}

			var before:Int = pos;
			args.push(parseExpr());
			if (pos == before)
				pos++;

			if (isSymbol(peek(), ","))
			{
				pos++;
				continue;
			}
			if (isSymbol(peek(), ")"))
			{
				pos++;
				break;
			}
			if (peek().kind == TkEof)
				break;

			warn(peek().line, "Expected ',' or ')' in the argument list");
			break;
		}
		return args;
	}

	function consumeRawStatement():Void
	{
		var startPos:Int = pos;
		var depth:Int = 0;
		var loopHeaders:Int = 0;

		while (peek().kind != TkEof)
		{
			var t:Token = peek();

			if (t.kind == TkName)
			{
				if (t.text == "function" || t.text == "if" || t.text == "for" || t.text == "while")
				{
					if (t.text == "for" || t.text == "while")
						loopHeaders++;
					depth++;
					pos++;
					continue;
				}
				if (t.text == "do")
				{
					if (loopHeaders > 0)
						loopHeaders--;
					else
						depth++;
					pos++;
					continue;
				}
				if (t.text == "end" || t.text == "until")
				{
					if (depth <= 0)
						return;
					pos++;
					depth--;
					if (depth <= 0)
						return;
					continue;
				}
			}

			if (depth <= 0 && pos > startPos && t.line > previousLine())
				return;

			pos++;
		}
	}

	// --- Expressions ---

	function parseExpr():Expr
	{
		return parseOr();
	}

	function parseOr():Expr
	{
		var begin:Int = peek().start;
		var left:Expr = parseAnd();
		while (isName(peek(), "or"))
		{
			pos++;
			var right:Expr = parseAnd();
			left = EBinop(src.substring(begin, lastFinish()), "or", left, right);
		}
		return left;
	}

	function parseAnd():Expr
	{
		var begin:Int = peek().start;
		var left:Expr = parseComparison();
		while (isName(peek(), "and"))
		{
			pos++;
			var right:Expr = parseComparison();
			left = EBinop(src.substring(begin, lastFinish()), "and", left, right);
		}
		return left;
	}

	function parseComparison():Expr
	{
		var begin:Int = peek().start;
		var left:Expr = parseConcat();
		while (isComparisonOperator(peek()))
		{
			var op:String = peek().text;
			pos++;
			var right:Expr = parseConcat();
			left = EBinop(src.substring(begin, lastFinish()), op, left, right);
		}
		return left;
	}

	function parseConcat():Expr
	{
		var begin:Int = peek().start;
		var left:Expr = parseAdd();
		while (isSymbol(peek(), ".."))
		{
			pos++;
			var right:Expr = parseAdd();
			left = EBinop(src.substring(begin, lastFinish()), "..", left, right);
		}
		return left;
	}

	function parseAdd():Expr
	{
		var begin:Int = peek().start;
		var left:Expr = parseMul();
		while (isSymbol(peek(), "+") || isSymbol(peek(), "-"))
		{
			var op:String = peek().text;
			pos++;
			var right:Expr = parseMul();
			left = EBinop(src.substring(begin, lastFinish()), op, left, right);
		}
		return left;
	}

	function parseMul():Expr
	{
		var begin:Int = peek().start;
		var left:Expr = parseUnary();
		while (isSymbol(peek(), "*") || isSymbol(peek(), "/") || isSymbol(peek(), "%"))
		{
			var op:String = peek().text;
			pos++;
			var right:Expr = parseUnary();
			left = EBinop(src.substring(begin, lastFinish()), op, left, right);
		}
		return left;
	}

	function parseUnary():Expr
	{
		var begin:Int = peek().start;
		if (isName(peek(), "not") || isSymbol(peek(), "-") || isSymbol(peek(), "#"))
		{
			var op:String = peek().text;
			pos++;
			var operand:Expr = parseUnary();
			return EUnop(src.substring(begin, lastFinish()), op, operand);
		}
		return parsePostfix();
	}

	function parsePostfix():Expr
	{
		var expr:Expr = parsePrimary();
		while (true)
		{
			if (isSymbol(peek(), "."))
			{
				var begin:Int = startOf(expr);
				pos++;
				var field:String = "";
				if (peek().kind == TkName)
				{
					field = peek().text;
					pos++;
				}
				else
					warn(peek().line, "Expected a field name after '.'");
				expr = EField(src.substring(begin, lastFinish()), expr, field);
				continue;
			}
			if (isSymbol(peek(), "["))
			{
				var begin2:Int = startOf(expr);
				pos++;
				var index:Expr = parseExpr();
				if (isSymbol(peek(), "]"))
					pos++;
				else
					warn(peek().line, "Expected ']'");
				expr = EIndex(src.substring(begin2, lastFinish()), expr, index);
				continue;
			}
			if (isSymbol(peek(), "("))
			{
				var begin3:Int = startOf(expr);
				pos++;
				var args:Array<Expr> = parseArgList();
				expr = ECall(src.substring(begin3, lastFinish()), calleeName(expr), args);
				continue;
			}
			if (isSymbol(peek(), ":"))
			{
				var begin4:Int = startOf(expr);
				pos++;
				var method:String = "";
				if (peek().kind == TkName)
				{
					method = peek().text;
					pos++;
				}
				var args2:Array<Expr> = [];
				if (isSymbol(peek(), "("))
				{
					pos++;
					args2 = parseArgList();
				}
				expr = ECall(src.substring(begin4, lastFinish()), calleeName(expr) + ":" + method, args2);
				continue;
			}
			break;
		}
		return expr;
	}

	function parsePrimary():Expr
	{
		var t:Token = peek();

		switch (t.kind)
		{
			case TkNumber:
				pos++;
				return ENumber(t.text, parseNumber(t.text));
			case TkString:
				pos++;
				return EString(t.text, t.value);
			case TkEof:
				warn(t.line, "Unexpected end of file inside an expression");
				return ERaw("");
			default:
		}

		if (isSymbol(t, "("))
		{
			pos++;
			var inner:Expr = parseExpr();
			if (isSymbol(peek(), ")"))
				pos++;
			else
				warn(t.line, "Expected ')'");
			return EGroup(src.substring(t.start, lastFinish()), inner);
		}

		if (isSymbol(t, "{"))
		{
			skipBalanced("{", "}");
			return ERaw(src.substring(t.start, lastFinish()));
		}

		if (isSymbol(t, "..."))
		{
			pos++;
			return ERaw(t.text);
		}

		if (t.kind == TkName)
		{
			pos++;
			if (t.text == "true")
				return EBool(t.text, true);
			if (t.text == "false")
				return EBool(t.text, false);
			return EIdent(t.text);
		}

		pos++;
		warn(t.line, "Unexpected token '" + shorten(t.text) + "' in an expression");
		return ERaw(t.text);
	}

	function skipBalanced(open:String, close:String):Void
	{
		var depth:Int = 0;
		while (peek().kind != TkEof)
		{
			var t:Token = peek();
			if (isSymbol(t, open))
				depth++;
			else if (isSymbol(t, close))
				depth--;
			pos++;
			if (depth <= 0)
				return;
		}
	}

	function parseNumber(raw:String):Float
	{
		if (raw.toLowerCase().startsWith("0x"))
		{
			var hex:Null<Int> = Std.parseInt(raw);
			return hex == null ? 0 : hex;
		}
		var value:Null<Float> = Std.parseFloat(raw);
		return value == null ? 0 : value;
	}

	// --- Blocks ---

	function stmtToNodes(stmt:PStmt, out:Array<Dynamic>):Void
	{
		switch (stmt)
		{
			case PCall(name, args, raw, line):
				var node:Dynamic = resolveStatementCall(name, args, raw, line);
				if (node == null)
				{
					warn(line, "'" + name + "(...)' is not a supported block here, it was imported as raw Lua code");
					node = runLuaCodeNode(raw);
				}
				out.push(node);

			case PAssign(target, value, raw, line):
				var node:Dynamic = makeNode("setVariable");
				node.inputs.push({index: 0, value: target});
				node.inputs.push({index: 1, value: exprToValue(value)});
				out.push(node);

			case PIf(cond, body, elseifs, elseBody, _, _):
				var ifNode:Dynamic = makeNode("if");
				ifNode.inputs.push({index: 0, value: exprToValue(cond)});
				out.push(ifNode);
				for (inner in body)
					stmtToNodes(inner, out);

				for (branch in elseifs)
				{
					var elseifNode:Dynamic = makeNode("elseif");
					elseifNode.inputs.push({index: 0, value: exprToValue(branch.cond)});
					out.push(elseifNode);
					for (inner in branch.body)
						stmtToNodes(inner, out);
				}

				if (elseBody != null)
				{
					out.push(makeNode("else"));
					for (inner in elseBody)
						stmtToNodes(inner, out);
				}

				out.push(makeNode("end"));

			case PWhile(cond, body, raw, line):
				var loopNode:Dynamic = whileNode(cond, raw, line);
				out.push(loopNode);
				if (loopNode.type == "whileTrue")
				{
					for (inner in body)
						stmtToNodes(inner, out);
					out.push(makeNode("end"));
				}

			case PBreak(_, _):
				out.push(makeNode("breakLoop"));

			case PRaw(text, _):
				out.push(runLuaCodeNode(text));
		}
	}

	function whileNode(cond:Expr, raw:String, line:Int):Dynamic
	{
		var clean:Expr = stripGroups(cond);
		var isPlainTrue:Bool = switch (clean)
		{
			case EBool(_, value): value;
			default: false;
		}

		var node:Dynamic = makeNode("whileTrue");
		if (isPlainTrue)
			return node;

		var data:BlockData = BlockLuaImporter.getBlockData("whileTrue");
		if (data != null && data.parameters != null && data.parameters.length > 0)
		{
			node.inputs.push({index: 0, value: exprToValue(clean)});
			warn(line, "The 'while' condition was attached to the whileTrue block");
			return node;
		}

		warn(line, "The 'while' condition cannot be represented as blocks, the loop was imported as raw Lua code");
		return runLuaCodeNode(raw);
	}

	function resolveStatementCall(name:String, args:Array<Expr>, raw:String, line:Int):Dynamic
	{
		var special:Dynamic = specialStatementCall(name, args);
		if (special != null)
			return special;

		var data:BlockData = BlockLuaImporter.getBlockData(name);
		var isStatement:Bool = STATEMENT_CALLS.indexOf(name) != -1 || (data != null && data.isReporter != true && data.isHat != true);
		if (isStatement)
		{
			var arity:Int = BlockLuaImporter.knownArity(name);
			if (arity < 0 || args.length <= arity)
				return parametricNode(name, args, data);
			warn(line, "'" + name + "' was called with " + args.length + " argument(s) but the block only has " + arity);
			return null;
		}

		if (data != null && data.isReporter == true)
		{
			// a reporter cannot stand on its own: the caller keeps the source line as raw Lua
			return null;
		}

		var generic:BlockData = BlockLuaImporter.getBlockData("callFunction");
		if (generic != null && templateMatchesCall(generic.lua, raw))
			return callFunctionNode(generic, name, raw);

		return null;
	}

	function specialStatementCall(name:String, args:Array<Expr>):Dynamic
	{
		switch (name)
		{
			case "runTimer":
				if (args.length == 2)
				{
					var node:Dynamic = makeNode("wait");
					node.inputs.push({index: 0, value: exprToValue(args[1])});
					return node;
				}
			case "setProperty":
				if (args.length == 2)
				{
					var tag:String = stringOf(stripGroups(args[0]));
					if (tag == "health")
					{
						var node:Dynamic = makeNode("setHealth");
						node.inputs.push({index: 0, value: exprToValue(args[1])});
						return node;
					}
					var prop:Dynamic = makeNode("setProperty");
					prop.inputs.push({index: 0, value: exprToValue(args[0])});
					prop.inputs.push({index: 1, value: exprToValue(args[1])});
					return prop;
				}
			case "close":
				var closeNode:Dynamic = makeNode("close");
				return closeNode;
			default:
		}
		return null;
	}

	function callToValue(name:String, args:Array<Expr>, raw:String):Dynamic
	{
		var special:Dynamic = specialValueCall(name, args);
		if (special != null)
			return special;

		var data:BlockData = BlockLuaImporter.getBlockData(name);
		var isReporter:Bool = REPORTER_CALLS.indexOf(name) != -1 || (data != null && data.isReporter == true && data.isHat != true);
		if (isReporter)
		{
			var arity:Int = BlockLuaImporter.knownArity(name);
			if (arity < 0 || args.length <= arity)
				return parametricNode(name, args, data);
		}

		return rawNode("luaExpression", raw);
	}

	function specialValueCall(name:String, args:Array<Expr>):Dynamic
	{
		if (name == "getProperty" && args.length == 1)
		{
			var tag:String = stringOf(stripGroups(args[0]));
			if (tag == "health")
				return makeNode("health");
		}
		if (name == "getSongPosition" && args.length == 0)
			return makeNode("songPosition");
		return null;
	}

	function exprToValue(expr:Expr):Dynamic
	{
		return switch (expr)
		{
			case ENumber(_, value): value;
			case EString(_, value): value;
			case EBool(_, value): value;
			case EIdent(raw):
				var reporter:Dynamic = identReporter(raw);
				reporter != null ? reporter : raw;
			case EGroup(_, inner): exprToValue(inner);
			case ECall(_, name, args): callToValue(name, args, rawOf(expr));
			case EBinop(_, op, left, right): binopToValue(op, left, right, rawOf(expr));
			case EUnop(_, op, operand): unopToValue(op, operand, rawOf(expr));
			case EField(_, _, _): rawOf(expr);
			case EIndex(_, _, _): rawOf(expr);
			case ERaw(raw): rawNode("luaExpression", raw);
		}
	}

	function identReporter(name:String):Dynamic
	{
		if (name == null || name.length == 0)
			return null;
		if (IDENT_EXCEPTIONS.indexOf(name) != -1)
			return null;
		if (!isLuaIdentifier(name))
			return null;

		var data:BlockData = BlockLuaImporter.getBlockData(name);
		if (data == null || data.isReporter != true)
			return null;
		if (data.parameters != null && data.parameters.length > 0)
			return null;
		if (data.lua != null && data.lua != name)
			return null;
		return makeNode(name);
	}

	function binopToValue(op:String, left:Expr, right:Expr, raw:String):Dynamic
	{
		var type:String = operatorBlock(op);
		if (type == null)
			return rawNode("luaExpression", raw);

		var data:BlockData = BlockLuaImporter.getBlockData(type);
		if (data != null && data.isReporter != true)
			return rawNode("luaExpression", raw);

		return parametricNode(type, [left, right], data);
	}

	function operatorBlock(op:String):String
	{
		return switch (op)
		{
			case "+": "add";
			case "-": "sub";
			case "*": "mul";
			case "/": "div";
			case "==": "eq";
			case ">": "gt";
			case "<": "lt";
			case "and": "and";
			case "or": "or";
			case "..": "join";
			default: null;
		}
	}

	function unopToValue(op:String, operand:Expr, raw:String):Dynamic
	{
		if (op != "not")
			return rawNode("luaExpression", raw);

		var data:BlockData = BlockLuaImporter.getBlockData("not");
		if (data != null && data.isReporter != true)
			return rawNode("luaExpression", raw);

		return parametricNode("not", [operand], data);
	}

	function parametricNode(type:String, args:Array<Expr>, data:BlockData):Dynamic
	{
		var node:Dynamic = makeNode(type);
		for (i in 0...args.length)
		{
			var isCode:Bool = false;
			if (data != null && data.parameters != null && i < data.parameters.length)
				isCode = (data.parameters[i].type == ParamType.CODE);
			node.inputs.push({
				index: i,
				value: isCode ? rawOf(stripGroups(args[i])) : exprToValue(args[i])
			});
		}
		return node;
	}

	function callFunctionNode(generic:BlockData, name:String, raw:String):Dynamic
	{
		var node:Dynamic = makeNode(generic.type);
		if (generic.parameters == null)
			return node;

		var argsText:String = argsTextOf(raw);
		var params:Array<BlockParameter> = generic.parameters;
		for (i in 0...params.length)
		{
			var param:BlockParameter = params[i];
			var lower:String = param.name.toLowerCase();
			var takesArgs:Bool = param.type == ParamType.CODE || lower.indexOf("arg") != -1 || lower.indexOf("param") != -1 || lower.indexOf("code") != -1
				|| lower.indexOf("lua") != -1;
			var takesName:Bool = lower.indexOf("name") != -1 || lower.indexOf("func") != -1 || lower.indexOf("call") != -1;

			var value:String = argsText;
			if (takesName && !takesArgs)
				value = name;
			else if (!takesArgs && params.length == 1)
				value = raw;

			node.inputs.push({index: i, value: value});
		}
		return node;
	}

	function argsTextOf(raw:String):String
	{
		var open:Int = raw.indexOf("(");
		var close:Int = raw.lastIndexOf(")");
		if (open < 0 || close <= open)
			return "";
		return raw.substring(open + 1, close).trim();
	}

	function templateMatchesCall(template:String, raw:String):Bool
	{
		if (template == null || template.length == 0)
			return true;

		var segments:Array<String> = [""];
		var i:Int = 0;
		while (i < template.length)
		{
			var c:String = template.charAt(i);
			if (c == "$")
			{
				segments.push("");
				i++;
				if (i < template.length && template.charAt(i) == "{")
				{
					var close:Int = template.indexOf("}", i);
					i = (close < 0) ? template.length : close + 1;
				}
				else
				{
					while (i < template.length && isDigit(template.charAt(i)))
						i++;
				}
				continue;
			}
			segments[segments.length - 1] += c;
			i++;
		}

		if (segments.length == 1)
			return template == raw;

		var cursor:Int = 0;
		for (k in 0...segments.length)
		{
			var segment:String = segments[k];
			if (segment.length == 0)
				continue;
			if (k == 0)
			{
				if (!raw.startsWith(segment))
					return false;
				cursor = segment.length;
				continue;
			}
			var found:Int = raw.indexOf(segment, cursor);
			if (found < 0)
				return false;
			cursor = found + segment.length;
		}
		return true;
	}

	function makeNode(type:String):Dynamic
	{
		return {
			type: type,
			x: 0,
			y: 0,
			inputs: [],
			next: null
		};
	}

	function runLuaCodeNode(text:String):Dynamic
	{
		return rawNode("runLuaCode", text == null ? "" : text);
	}

	function rawNode(type:String, raw:String):Dynamic
	{
		var node:Dynamic = makeNode(type);
		node.inputs.push({index: 0, value: raw == null ? "" : raw});
		return node;
	}

	// --- Layout ---

	function layoutAll():Void
	{
		var slot:Int = 0;
		for (root in stacks)
		{
			placeStack(root, slot);
			slot++;
		}
		for (entry in timeline)
		{
			if (entry.stack != null)
			{
				placeStack(entry.stack, slot);
				slot++;
			}
		}
	}

	function placeStack(root:Dynamic, slot:Int):Void
	{
		if (root == null)
			return;

		var column:Int = slot % BlockLuaImporter.STACK_COLUMNS;
		var row:Int = Std.int(slot / BlockLuaImporter.STACK_COLUMNS);
		var x:Float = BlockLuaImporter.BASE_X + column * BlockLuaImporter.STACK_COLUMN_STEP;
		var y:Float = BlockLuaImporter.BASE_Y + row * BlockLuaImporter.STACK_ROW_STEP;

		var node:Dynamic = root;
		var index:Int = 0;
		while (node != null)
		{
			node.x = x;
			node.y = y + index * BlockLuaImporter.STACK_CHAIN_STEP;
			placeInputs(node);
			index++;
			node = node.next;
		}
	}

	function placeInputs(node:Dynamic):Void
	{
		var inputs:Array<Dynamic> = node.inputs;
		if (inputs == null)
			return;

		for (input in inputs)
		{
			var value:Dynamic = input.value;
			if (!isNode(value))
				continue;
			value.x = node.x;
			value.y = node.y;
			placeInputs(value);
		}
	}

	function isNode(value:Dynamic):Bool
	{
		if (value == null)
			return false;
		if (Std.isOfType(value, String) || Std.isOfType(value, Float) || Std.isOfType(value, Int) || Std.isOfType(value, Bool))
			return false;
		return Reflect.hasField(value, "type") && Reflect.hasField(value, "inputs");
	}

	// --- Helpers ---

	function chainNodes(nodes:Array<Dynamic>):Dynamic
	{
		if (nodes == null || nodes.length == 0)
			return null;

		var out:Array<Dynamic> = [];
		for (node in nodes)
		{
			if (node != null)
				out.push(node);
		}
		if (out.length == 0)
			return null;

		for (i in 0...(out.length - 1))
			out[i].next = out[i + 1];
		out[out.length - 1].next = null;
		return out[0];
	}

	function warn(line:Int, message:String):Void
	{
		if (warnings.length >= BlockLuaImporter.MAX_WARNINGS)
			return;

		var text:String = (line > 0) ? "Line " + line + ": " + message : message;
		if (!warnings.contains(text))
			warnings.push(text);
	}

	function peek():Token
	{
		return tokens[pos];
	}

	function peekAt(offset:Int):Token
	{
		var index:Int = pos + offset;
		if (index < 0)
			index = 0;
		if (index >= tokens.length)
			index = tokens.length - 1;
		return tokens[index];
	}

	function previousLine():Int
	{
		return pos > 0 ? tokens[pos - 1].line : 0;
	}

	function lastFinish():Int
	{
		return pos > 0 ? tokens[pos - 1].finish : 0;
	}

	function isName(token:Token, name:String):Bool
	{
		return token.kind == TkName && token.text == name;
	}

	function isSymbol(token:Token, symbol:String):Bool
	{
		return token.kind == TkSymbol && token.text == symbol;
	}

	function isComparisonOperator(token:Token):Bool
	{
		if (token.kind != TkSymbol)
			return false;
		return token.text == "==" || token.text == "~=" || token.text == "<" || token.text == ">" || token.text == "<=" || token.text == ">=";
	}

	function atStatementEnd():Bool
	{
		var t:Token = peek();
		if (t.kind == TkEof)
			return true;
		if (isSymbol(t, ";"))
			return true;
		if (t.kind == TkName && STATEMENT_STOPS.indexOf(t.text) != -1)
			return true;
		return t.line > previousLine();
	}

	function consumeSemicolon():Void
	{
		if (isSymbol(peek(), ";"))
			pos++;
	}

	function skipToLineEnd():Void
	{
		if (peek().kind == TkEof)
			return;

		var line:Int = peek().line;
		while (peek().kind != TkEof)
		{
			var t:Token = peek();
			if (t.line != line)
				return;
			if (t.kind == TkName && STATEMENT_STOPS.indexOf(t.text) != -1)
				return;
			pos++;
		}
	}

	function expectName(name:String):Void
	{
		if (isName(peek(), name))
			pos++;
		else
			warn(peek().line, "Expected '" + name + "'");
	}

	function calleeName(expr:Expr):String
	{
		return switch (expr)
		{
			case EIdent(raw): raw;
			default: rawOf(expr);
		}
	}

	function startOf(expr:Expr):Int
	{
		var raw:String = rawOf(expr);
		if (raw.length == 0)
			return lastFinish();
		var index:Int = src.lastIndexOf(raw, (pos > 0) ? tokens[pos - 1].finish : src.length);
		return (index < 0) ? lastFinish() : index;
	}

	function stripGroups(expr:Expr):Expr
	{
		return switch (expr)
		{
			case EGroup(_, inner): stripGroups(inner);
			default: expr;
		}
	}

	function rawOf(expr:Expr):String
	{
		return switch (expr)
		{
			case ENumber(raw, _): raw;
			case EString(raw, _): raw;
			case EBool(raw, _): raw;
			case EIdent(raw): raw;
			case EField(raw, _, _): raw;
			case EIndex(raw, _, _): raw;
			case ECall(raw, _, _): raw;
			case EBinop(raw, _, _, _): raw;
			case EUnop(raw, _, _): raw;
			case EGroup(raw, _): raw;
			case ERaw(raw): raw;
		}
	}

	function shorten(text:String):String
	{
		if (text == null)
			return "";
		var clean:String = text.replace("\n", " ").trim();
		return clean.length > 24 ? clean.substr(0, 24) + "..." : clean;
	}

	function isLuaIdentifier(name:String):Bool
	{
		if (name.length == 0 || KEYWORDS.indexOf(name) != -1)
			return false;
		if (!isIdentStart(name.charAt(0)))
			return false;
		for (i in 1...name.length)
		{
			if (!isIdentChar(name.charAt(i)))
				return false;
		}
		return true;
	}

	static function isWhitespace(c:String):Bool
	{
		return c == " " || c == "\t" || c == "\n" || c == "\r" || c == String.fromCharCode(12) || c == String.fromCharCode(11);
	}

	function countLines(text:String):Int
	{
		var total:Int = 0;
		for (i in 0...text.length)
		{
			if (text.charAt(i) == "\n")
				total++;
		}
		return total;
	}

	function repeatChar(c:String, times:Int):String
	{
		var out:String = "";
		for (_ in 0...times)
			out += c;
		return out;
	}

	static function isDigit(c:String):Bool
	{
		return c.length == 1 && c >= "0" && c <= "9";
	}

	static function isHexDigit(c:String):Bool
	{
		return isDigit(c) || (c >= "a" && c <= "f") || (c >= "A" && c <= "F");
	}

	static function isIdentStart(c:String):Bool
	{
		return (c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || c == "_";
	}

	static function isIdentChar(c:String):Bool
	{
		return isIdentStart(c) || isDigit(c);
	}
}
