package editors.blockcode;

import editors.blockcode.BlockTypes;
#if sys
import sys.FileSystem;
import sys.io.File;
#end

using StringTools;

/**
 * Disk side of the block-code editor: where the generated Lua is written, how it is
 * named, renamed, listed and read back.
 *
 * Every path handed back to the UI is a forward-slash path (relative to the game folder
 * on desktop, storage-prefixed on Android, absolute when the user typed an absolute
 * `customExecPath`); the platform separator is only applied right before an actual file
 * operation.
 *
 * All disk access sits behind `#if sys` and inside `try/catch`, so on HTML5 - and when
 * `mods/` does not exist yet - the readers return `""` / `[]` and `save` reports failure
 * instead of throwing. An existing target that was not written by the editor is copied
 * to `<file>.lua.bak` before it is overwritten, so hand written scripts are never lost.
 */
class BlockFileIO
{
	/** First line of every script the editor generates; marks a file as safe to overwrite. */
	static var GENERATED_HEADER:String = '-- Generated by Parker Engine Block Editor';

	/** Mod folder used when no mod is active (`Paths.currentModDirectory` is empty). */
	static var FALLBACK_MOD:String = 'blockcode';

	/** How deep `listScripts` walks into each candidate folder. */
	static var MAX_SCAN_DEPTH:Int = 3;

	#if sys
	static var WINDOWS:Bool = Sys.systemName() == 'Windows';
	#end

	// --- Naming ---

	/**
	 * Turns free text into a usable file name: lowercase, spaces become dashes and
	 * everything outside `[a-z0-9-_]` is dropped. A trailing `.lua` is ignored and an
	 * empty result falls back to `BlockTypes.DEFAULT_SCRIPT_NAME`.
	 */
	public static function sanitizeName(name:String):String
	{
		if (name == null)
			return BlockTypes.DEFAULT_SCRIPT_NAME;

		var clean:String = name.trim().toLowerCase();
		if (clean.endsWith('.lua'))
			clean = clean.substring(0, clean.length - 4);

		clean = clean.replace(' ', '-');
		clean = ~/[^a-z0-9\-_]/g.replace(clean, '');
		clean = ~/-{2,}/g.replace(clean, '-');

		var start:Int = 0;
		var end:Int = clean.length;
		while (start < end && clean.charAt(start) == '-')
			start++;
		while (end > start && clean.charAt(end - 1) == '-')
			end--;
		clean = clean.substring(start, end);

		return clean.length > 0 ? clean : BlockTypes.DEFAULT_SCRIPT_NAME;
	}

	// --- Paths ---

	/**
	 * Folder the script is written to. `song` mode targets the song's data folder when a
	 * song name is known (and the mod's `scripts` folder otherwise), `global` mode always
	 * targets `scripts` and `custom` mode uses `customExecPath` (falling back to
	 * `savePath`, then to the mod's `scripts` folder).
	 */
	public static function resolveDir(s:BlockCodeEditorSettings, ?songName:String):String
	{
		var mode:String = (s == null || s.execMode == null) ? 'song' : s.execMode;
		switch (mode)
		{
			case 'global':
				return modScriptsDir();
			case 'custom':
				return customDir(s);
			default:
				var song:String = songFolder(songName);
				return song.length > 0 ? joinPaths(modRoot(), 'data/' + song) : modScriptsDir();
		}
	}

	/** Full path (including `.lua`) the current settings save to. */
	public static function resolveTarget(s:BlockCodeEditorSettings, ?songName:String):String
	{
		if (s != null && s.execMode == 'custom')
		{
			var custom:String = s.customExecPath == null ? '' : toSlash(s.customExecPath.trim());
			if (custom.length > 4 && custom.toLowerCase().endsWith('.lua'))
				return custom;
		}
		return joinPaths(resolveDir(s, songName), sanitizeName(s == null ? null : s.scriptName) + '.lua');
	}

	/** Human readable location for the settings panel, e.g. `mods/blockcode/scripts/blockcode.lua  (global script)`. */
	public static function describe(s:BlockCodeEditorSettings, ?songName:String):String
	{
		var target:String = resolveTarget(s, songName);
		if (target.length < 1)
			return '';
		return target + '  (' + modeLabel(s == null ? null : s.execMode) + ')';
	}

	/**
	 * The concrete target of each exec mode with the default script name, in the order
	 * song / global / custom - for the settings panel to show what every mode would use.
	 */
	public static function execTargetsFor(songName:String):Array<String>
	{
		var targets:Array<String> = [];
		for (mode in ['song', 'global', 'custom'])
		{
			var settings:BlockCodeEditorSettings = BlockTypes.defaultSettings();
			settings.execMode = mode;
			targets.push(resolveTarget(settings, songName));
		}
		return targets;
	}

	static function modeLabel(mode:String):String
	{
		switch (mode)
		{
			case 'global':
				return 'global script';
			case 'custom':
				return 'custom path';
			default:
				return 'song script';
		}
	}

	static function songFolder(?songName:String):String
		return songName == null ? '' : Paths.formatToSongPath(songName.trim());

	static function activeMod():String
	{
		var mod:String = Paths.currentModDirectory;
		return (mod != null && mod.length > 0) ? mod : FALLBACK_MOD;
	}

	static function modsRoot():String
	{
		#if MODS_ALLOWED
		return stripTrailingSlashes(Paths.mods());
		#else
		return stripTrailingSlashes(toSlash(SUtil.getPath() + 'mods/'));
		#end
	}

	static function modRoot():String
		return joinPaths(modsRoot(), activeMod());

	static function modScriptsDir():String
		return joinPaths(modRoot(), 'scripts');

	static function customDir(s:BlockCodeEditorSettings):String
	{
		var raw:String = (s == null || s.customExecPath == null) ? '' : s.customExecPath.trim();
		if (raw.length < 1 && s != null && s.savePath != null)
			raw = s.savePath.trim();
		if (raw.length < 1)
			return modScriptsDir();

		var path:String = stripTrailingSlashes(toSlash(raw));
		if (path.length > 4 && path.toLowerCase().endsWith('.lua'))
			path = parentDir(path);
		return path;
	}

	// --- Reading and writing ---

	/**
	 * Writes `code` to the resolved target, creating missing folders. A target that was
	 * not generated by the editor is backed up to `<file>.lua.bak` first.
	 * Returns the written path, or `""` when the write failed.
	 */
	public static function save(s:BlockCodeEditorSettings, code:String, ?songName:String):String
	{
		if (s == null || code == null)
			return '';

		var target:String = resolveTarget(s, songName);
		if (target.length < 1)
			return '';

		#if sys
		try
		{
			var native:String = toNative(target);
			if (!ensureDir(parentDir(target)))
				return '';

			backupIfNeeded(native);
			File.saveContent(native, ensureHeader(code));
			if (!FileSystem.exists(native))
				return '';

			return toSlash(target);
		}
		catch (e:Dynamic)
		{
			trace('BlockFileIO: could not save "$target": $e');
			return '';
		}
		#else
		return '';
		#end
	}

	/**
	 * Moves the file the current settings point at to `newName` and stores that name in
	 * `s.scriptName` (a `customExecPath` naming a `.lua` file is renamed with it). The new
	 * path is always returned - when there is nothing to move yet, the next save creates it.
	 */
	public static function rename(s:BlockCodeEditorSettings, newName:String, ?songName:String):String
	{
		if (s == null)
			return '';

		var oldPath:String = resolveTarget(s, songName);
		var clean:String = sanitizeName(newName);
		s.scriptName = clean;

		var custom:String = (s.customExecPath == null) ? '' : toSlash(s.customExecPath.trim());
		if (s.execMode == 'custom' && custom.length > 4 && custom.toLowerCase().endsWith('.lua'))
			s.customExecPath = joinPaths(parentDir(custom), clean + '.lua');

		var newPath:String = resolveTarget(s, songName);

		#if sys
		if (oldPath != newPath)
		{
			try
			{
				moveFile(oldPath, newPath);
			}
			catch (e:Dynamic)
			{
				trace('BlockFileIO: could not rename "$oldPath" to "$newPath": $e');
			}
		}
		#end
		return newPath;
	}

	/** Content of `path`, or `""` when it is missing, unreadable or the target has no filesystem. */
	public static function read(path:String):String
	{
		#if sys
		if (path == null || path.length < 1)
			return '';

		try
		{
			var native:String = toNative(path);
			if (!FileSystem.exists(native) || FileSystem.isDirectory(native))
				return '';

			return File.getContent(native);
		}
		catch (e:Dynamic)
		{
			trace('BlockFileIO: could not read "$path": $e');
			return '';
		}
		#else
		return '';
		#end
	}

	/** True when `path` names an existing file. Always false on targets without a filesystem. */
	public static function exists(path:String):Bool
	{
		#if sys
		if (path == null || path.length < 1)
			return false;

		try
		{
			var native:String = toNative(path);
			return FileSystem.exists(native) && !FileSystem.isDirectory(native);
		}
		catch (e:Dynamic)
		{
			return false;
		}
		#else
		return false;
		#end
	}

	/**
	 * Every `.lua` the engine could load for a song: `<mods>/<mod>/scripts`,
	 * `<mods>/<mod>/data/<song>` and `<mods>/<mod>/blockcode` for the shared mods root and
	 * for every mod folder found next to it. Mod folders do not need a `pack.json`.
	 * Forward-slash paths, sorted; empty when `mods/` does not exist.
	 */
	public static function listScripts(?songName:String):Array<String>
	{
		var found:Array<String> = [];
		#if sys
		try
		{
			var root:String = modsRoot();
			if (!isDirectory(root))
				return found;

			var folders:Array<String> = ['scripts', 'blockcode'];
			var song:String = songFolder(songName);
			if (song.length > 0)
				folders.push('data/' + song);

			var bases:Array<String> = [root];
			for (mod in subFolders(root))
				bases.push(joinPaths(root, mod));

			for (base in bases)
			{
				for (folder in folders)
					scanFolder(joinPaths(base, folder), 0, found);
			}
			found.sort(Reflect.compare);
		}
		catch (e:Dynamic)
		{
			trace('BlockFileIO: could not list scripts: $e');
		}
		#end
		return found;
	}

	// --- Filesystem helpers ---

	static function moveFile(oldPath:String, newPath:String):Void
	{
		#if sys
		var oldNative:String = toNative(oldPath);
		var newNative:String = toNative(newPath);
		if (newNative.length < 1 || oldNative == newNative)
			return;
		if (!FileSystem.exists(oldNative) || FileSystem.isDirectory(oldNative))
			return;
		if (!ensureDir(parentDir(newPath)))
			return;

		if (FileSystem.exists(newNative))
		{
			// never clobber a directory, and a case-only rename points at the same file
			if (FileSystem.isDirectory(newNative) || oldNative.toLowerCase() == newNative.toLowerCase())
				return;

			backupIfNeeded(newNative);
			FileSystem.deleteFile(newNative);
		}

		try
		{
			FileSystem.rename(oldNative, newNative);
		}
		catch (e:Dynamic)
		{
			// rename can fail across volumes or when the target is locked, so fall back to a copy
			File.saveContent(newNative, File.getContent(oldNative));
			FileSystem.deleteFile(oldNative);
		}
		#end
	}

	/** Copies a target the editor did not generate aside before it gets overwritten. */
	static function backupIfNeeded(nativePath:String):Void
	{
		#if sys
		try
		{
			if (!FileSystem.exists(nativePath) || FileSystem.isDirectory(nativePath))
				return;

			var content:String = File.getContent(nativePath);
			if (content.startsWith(GENERATED_HEADER))
				return;

			File.saveContent(nativePath + '.bak', content);
		}
		catch (e:Dynamic)
		{
			trace('BlockFileIO: could not back up "$nativePath": $e');
		}
		#end
	}

	static function ensureHeader(code:String):String
		return code.startsWith(GENERATED_HEADER) ? code : GENERATED_HEADER + '\n\n' + code;

	/** Creates `dir` and every missing parent. `true` when the folder exists afterwards. */
	static function ensureDir(dir:String):Bool
	{
		#if sys
		var path:String = stripTrailingSlashes(toSlash(dir));
		if (path.length < 1)
			return true;

		try
		{
			var native:String = toNative(path);
			if (FileSystem.exists(native))
				return FileSystem.isDirectory(native);

			var parent:String = parentDir(path);
			if (parent.length > 0 && parent != path && !ensureDir(parent))
				return false;

			FileSystem.createDirectory(native);
			return FileSystem.isDirectory(native);
		}
		catch (e:Dynamic)
		{
			trace('BlockFileIO: could not create "$dir": $e');
			return false;
		}
		#else
		return false;
		#end
	}

	/** Collects `*.lua` files of `dir` and of its sub folders (up to `MAX_SCAN_DEPTH`). */
	static function scanFolder(dir:String, depth:Int, out:Array<String>):Void
	{
		#if sys
		if (depth > MAX_SCAN_DEPTH || !isDirectory(dir))
			return;

		try
		{
			for (name in FileSystem.readDirectory(toNative(dir)))
			{
				if (name == null || name.length < 1 || name.startsWith('.'))
					continue;

				var child:String = joinPaths(dir, name);
				if (isDirectory(child))
				{
					scanFolder(child, depth + 1, out);
					continue;
				}

				if (name.toLowerCase().endsWith('.lua') && !out.contains(child))
					out.push(child);
			}
		}
		catch (e:Dynamic)
		{
			trace('BlockFileIO: could not read "$dir": $e');
		}
		#end
	}

	static function subFolders(dir:String):Array<String>
	{
		var folders:Array<String> = [];
		#if sys
		if (!isDirectory(dir))
			return folders;

		try
		{
			for (name in FileSystem.readDirectory(toNative(dir)))
			{
				if (name == null || name.length < 1 || name.startsWith('.'))
					continue;
				if (isDirectory(joinPaths(dir, name)))
					folders.push(name);
			}
		}
		catch (e:Dynamic)
		{
			trace('BlockFileIO: could not read "$dir": $e');
		}
		folders.sort(Reflect.compare);
		#end
		return folders;
	}

	static function isDirectory(path:String):Bool
	{
		#if sys
		var native:String = toNative(path);
		if (native.length < 1)
			return false;

		try
		{
			return FileSystem.exists(native) && FileSystem.isDirectory(native);
		}
		catch (e:Dynamic)
		{
			return false;
		}
		#else
		return false;
		#end
	}

	static inline function toSlash(path:String):String
		return path == null ? '' : path.replace('\\', '/');

	/** Slash paths are for display, the platform separator is for the file operations. */
	static inline function toNative(path:String):String
	{
		#if sys
		var slash:String = toSlash(path);
		return WINDOWS ? slash.replace('/', '\\') : slash;
		#else
		return toSlash(path);
		#end
	}

	static function parentDir(path:String):String
	{
		var slash:String = toSlash(path);
		var index:Int = slash.lastIndexOf('/');
		return index < 0 ? '' : slash.substring(0, index);
	}

	static function stripTrailingSlashes(path:String):String
	{
		var slash:String = toSlash(path);
		var end:Int = slash.length;
		while (end > 1 && slash.charAt(end - 1) == '/')
			end--;
		return slash.substring(0, end);
	}

	static function joinPaths(left:String, right:String):String
	{
		var a:String = toSlash(left);
		var b:String = toSlash(right);
		if (a.length < 1)
			return b;
		if (b.length < 1)
			return stripTrailingSlashes(a);

		while (b.startsWith('/'))
			b = b.substring(1);
		return stripTrailingSlashes(a) + '/' + b;
	}
}
